services:
  gameserver:
    image: balkshamster/looperlands:latest
    ports:
      - "8000:443"
    env_file:
      - /home/looperlands/.env
  gameserver2:
    image: balkshamster/looperlands:latest
    ports:
      - "8000:443"
    env_file:
      - /home/looperlands/.env2
