FROM ubuntu:22.04
ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV DEBIAN_FRONTEND noninteractive
ARG MAP_FILE
RUN apt -y update
RUN apt -q -y install curl
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION v20.9.0
RUN mkdir -p /usr/local/nvm && apt-get update && echo "y" | apt-get install curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm use --delete-prefix $NODE_VERSION"
ENV NODE_PATH $NVM_DIR/versions/node/$NODE_VERSION/bin
ENV PATH $NODE_PATH:$PATH
RUN apt-get update -yq \
    && apt-get install curl gnupg python2 zip unzip -yq \
    && curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py \
    && python2 get-pip.py \
    && python2 -m pip install lxml

COPY . /opt/app
WORKDIR /opt/app
COPY shared/js/gametypes.js client/js/gametypes.js
RUN npm ci
WORKDIR /opt/app/tools/maps
RUN echo Map file ${MAP_FILE}
RUN python2 ./export.py server ${MAP_FILE} && python2 ./export.py client ${MAP_FILE}
RUN zip -r /opt/app/maps.zip /opt/app/client/maps /opt/app/server/maps