FROM ubuntu:latest
ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV DEBIAN_FRONTEND noninteractive
ARG MAP_FILE
RUN apt -y update
RUN apt -q -y install curl
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION v20.9.0
RUN mkdir -p /usr/local/nvm && apt-get update && echo "y" | apt-get install curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm use --delete-prefix $NODE_VERSION"
ENV NODE_PATH $NVM_DIR/versions/node/$NODE_VERSION/bin
ENV PATH $NODE_PATH:$PATH
RUN apt-get update -yq \
    && apt-get install gnupg python3 python3-pip python3-lxml zip unzip -yq

WORKDIR /opt/app
COPY package*.json /opt/app
RUN npm ci
COPY . /opt/app
WORKDIR /opt/app/tools/maps
RUN echo Map file ${MAP_FILE}
RUN python3 ./export.py server ${MAP_FILE} && python3 ./export.py client ${MAP_FILE}
RUN zip -r /opt/app/maps.zip /opt/app/client/maps /opt/app/server/maps