FROM node:20-bookworm
ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV DEBIAN_FRONTEND=noninteractive
ARG MAP_FILE

WORKDIR /opt/app
COPY . /opt/app
WORKDIR /opt/app/tools/maps
RUN echo Map file ${MAP_FILE}
RUN python3 ./export.py server ${MAP_FILE} && python3 ./export.py client ${MAP_FILE}
