#!/bin/bash
if [ -z "$LOOPWORMS_API_KEY" ]
  then
    echo "Missing LOOPWORMS_API_KEY environment variable"
    exit 1
fi

if [ -z "$LOOPWORMS_LOOPERLANDS_BASE_URL" ]
  then
    echo "Missing LOOPWORMS_LOOPERLANDS_BASE_URL environment variable"
    exit 1
fi
export DOCKER_DEFAULT_PLATFORM=linux/amd64
IP=${LOCAL_IP:-127.0.0.1}
export APP_URL="http://$IP:8000"
export GAMESERVER_NAME="local-test"
docker build . -t looperlands-gameserver && docker run -e LOOPWORMS_API_KEY=$LOOPWORMS_API_KEY -e LOOPWORMS_LOOPERLANDS_BASE_URL=$LOOPWORMS_LOOPERLANDS_BASE_URL -e DISCORD_TOKEN=$DISCORD_TOKEN -e LOOPERLANDS_BACKEND_BASE_URL=$LOOPERLANDS_BACKEND_BASE_URL -e LOOPERLANDS_BACKEND_API_KEY=$LOOPERLANDS_BACKEND_API_KEY -e APP_URL=$APP_URL -e LOOPERLANDS_PLATFORM_BASE_URL=$LOOPERLANDS_PLATFORM_BASE_URL -e LOOPERLANDS_PLATFORM_API_KEY=$LOOPERLANDS_PLATFORM_API_KEY -e GAMESERVER_NAME=$GAMESERVER_NAME -t -i -p 8000:8000 -t looperlands-gameserver
