"""Pack imagegen's 5-column/3-direction attack sheets into the weapon layout.

Usage: python3 tools/sprites/pack-tool-sheets.py SOURCE SPRITE_ID
Requires Pillow. Artwork is generated by imagegen; this only packs/resizes frames.
"""
import json
import sys
from pathlib import Path
from PIL import Image

source, name = sys.argv[1:3]
art_size = int(sys.argv[3]) if len(sys.argv) > 3 else 48
# Optional per-direction offsets align the artwork with the existing character grip.
offsets = json.loads(sys.argv[4]) if len(sys.argv) > 4 else [[0, 0]] * 3
root = Path(__file__).resolve().parents[2]
image = Image.open(source).convert('RGBA')
sheet = Image.new('RGBA', (240, 432))
animations = {}
for direction, row in [('right', 0), ('up', 1), ('down', 2)]:
    frames = []
    for column in range(5):
        cell = image.crop((round(column * image.width / 5), round(row * image.height / 3),
                           round((column + 1) * image.width / 5), round((row + 1) * image.height / 3)))
        # Preserve the whole cell, so the generated pose remains anchored consistently.
        # Keep generated artwork intact while fitting it into a native weapon frame.
        frame = Image.new('RGBA', (48, 48))
        art = cell.resize((art_size, art_size), Image.Resampling.NEAREST)
        dx, dy = offsets[row]
        frame.paste(art, ((48 - art_size) // 2 + dx, (48 - art_size) // 2 + dy))
        frames.append(frame)
    base = row * 3
    for column, frame in enumerate(frames):
        sheet.paste(frame, (column * 48, base * 48))
    for offset, length, action in [(1, 4, 'walk'), (2, 2, 'idle')]:
        for column in range(length):
            sheet.paste(frames[0], (column * 48, (base + offset) * 48))
        animations[f'{action}_{direction}'] = {'length': length, 'row': base + offset}
    animations[f'atk_{direction}'] = {'length': 5, 'row': base}
for scale in (1, 2, 3):
    sheet.resize((240 * scale, 432 * scale), Image.Resampling.NEAREST).save(root / f'client/img/{scale}/{name}.png')
(root / f'client/sprites/{name}.json').write_text(json.dumps({
    'id': name, 'width': 48, 'height': 48, 'animations': animations,
    'offset_x': -16, 'offset_y': -20,
}, indent=2) + '\n')
