// Production campaign, content version 1. Quest IDs and choice keys are save contracts.
// Every location is on main, including the existing door-connected interiors.
const Types = require('../../shared/js/gametypes');
const picnic = require('./lantern-picnic');
const I = picnic.INVITE;
const at = (key, label, x, y, scene, result, extra = {}) => ({key, label, x, y, scene, result, type: 'inspect', ...extra});
const kill = (key, label, kinds, amount, scene, result) => ({key, label, kinds, amount, scene, result, type: 'kill'});
const pick = (label, flag, response) => ({label, flag, response});
const quest = (id, chapter, name, npcKey, requiredQuests, reason, objectives, conclusion, extra = {}) => ({
    id: 'LANTERN_' + id, chapter, name, npcKey, requiredQuests, reason, objectives, conclusion,
    eventType: 'NPC_TALKED', target: 'FLOW', amount: 1, level: 1, dialogueOnly: true, ...extra
});
const npcs = [
    {key: 'town-gardener', kind: 'villager', label: 'Ordinary Adam', x: 37, y: 200},
    {key: 'town-neighbour', kind: 'villagegirl', label: 'Bstrat515', x: 15, y: 222},
    {key: 'town-watch', kind: 'guard', label: 'Town Watch', x: 73, y: 197},
    {key: 'coastal-jimi', kind: 'beachnpc', label: 'Jimi', x: 76, y: 293},
    {key: 'mill-scientist', kind: 'scientist', label: 'Windmill Scientist', x: 127, y: 293},
    {key: 'forest-caretaker', kind: 'forestnpc', label: 'Mara, Trail Caretaker', x: 58, y: 176, spawn: true},
    {key: 'town-priest', kind: 'priest', label: 'Vince', x: 18, y: 209},
    {key: 'desert-courier', kind: 'villagegirl', label: 'Nessa, Caravan Courier', x: 47, y: 94, spawn: true},
    {key: 'north-miner', kind: 'miner', label: 'Northern Miner', x: 106, y: 6},
    {key: 'north-technician', kind: 'lavanpc', label: 'Orin, Relay Technician', x: 97, y: 29, spawn: true},
    {key: 'lantern-keeper', kind: 'villager', label: 'Rowan, Lantern Keeper', x: 67, y: 378, spawn: true},
    {key: 'party-wildwill', kind: 'wildwill', label: 'Wild Will', x: 35, y: 463}
];

const chapters = [
    {number: 1, name: 'The Lantern Picnic'},
    {number: 2, name: 'Letters from the Coast'},
    {number: 3, name: 'The Forest Still Remembers'},
    {number: 4, name: 'A Light for the Missing'},
    {number: 5, name: 'The Last Delivery'},
    {number: 6, name: 'Heat Without Light'},
    {number: 7, name: 'The Keeper of the Road'},
    {number: 8, name: 'The Long Table'}
];

const quests = [
    quest('WRECK_LETTERS', 2, 'Letters in the Wreckage', 'coastal-jimi', [I],
        'Adam saved an empty place at the picnic. Jimi remembers Rowan bringing invitations along the shore; a storm stranded the last delivery.',
        [at('letters', 'Recover the weathered invitation pouch', 53, 285, 'Beach',
            'The letters were addressed to the forest, desert and northern works. Nobody chose to abandon Town: the delivery never arrived.')],
        'Jimi recognises Rowan\'s handwriting. A broken coastal signal kept the courier from finding a safe landing.',
        {choices: [pick('Repair the coastal signal first.', 'lantern:coast-first', 'Jimi will keep the recovered letters dry while you make the crossing safe.'),
            pick('Check on the stranded travellers first.', 'lantern:travellers-first', 'Jimi points out the waiting place east of the signal. Their safety comes before the repair.')]}),
    quest('MILL_LIGHT', 2, 'The Mill Without a Light', 'mill-scientist', ['LANTERN_WRECK_LETTERS'],
        'The scientist stayed at the mill because its lantern no longer receives a signal. Enter the windmill from southern Town to inspect the receiver.',
        [at('receiver', 'Inspect the mill receiver', 127, 295, 'Windmill', 'The gears still turn. The disconnected receiver, not the mill itself, stopped the light.')],
        'The scientist gives you a repaired connector and a map of the coastal relay. The fault continues inland into the forest.'),
    quest('COAST_SIGNAL', 2, 'A Signal Across the Water', 'coastal-jimi', ['LANTERN_MILL_LIGHT'],
        'The mill connector can restore the coastal relay. Your earlier decision explains which task the travellers expect you to do first.',
        [at('travellers', 'Check the stranded travellers\' waiting place', 62, 264, 'Beach', 'The travellers have water and a safe waiting place. They ask you to pass their invitations onward.',
            {when: 'lantern:travellers-first'}),
         at('relay', 'Fit the connector to the coastal relay', 57, 260, 'Beach', 'The coastal lantern glows again. Its next marker points north to Mara in the forest.')],
        'Jimi can guide the next landing because you repaired the signal. He promises to bring a basket of sea-salt bread when the road opens.'),
    quest('FOREST_MARKERS', 3, 'Follow the Old Markers', 'forest-caretaker', [I],
        'Mara maintains the old paths, but stopped sending invitations when no reply came. She needs evidence from the markers before blaming the neighbours.',
        [at('south', 'Read the southern trail marker', 43, 176, 'Forest', 'The scratched arrow still points toward Town.'),
         at('north', 'Read the northern trail marker', 34, 150, 'Forest', 'A keeper\'s knot marks the route to the relay. The trails were connected deliberately, not forgotten.')],
        'Mara recognises both markers. Rowan once taught her the knots; she now suspects a deliberate closure.'),
    quest('KEEPER_KNOTS', 3, 'The Keeper\'s Knots', 'forest-caretaker', ['LANTERN_FOREST_MARKERS'],
        'Mara will stay on the trail to guide other walkers. Inspect the forest relay to find why its signal vanished.',
        [at('relay', 'Examine the tied-off forest relay', 74, 154, 'Forest', 'The relay was carefully disconnected. A note says: "Keep them away until the north is safe." It was signed Rowan.')],
        'Mara waits here because walkers still need a safe guide. Rowan was trying to protect people, but never explained the danger.'),
    quest('STILL_WAITING', 3, 'Someone Is Still Waiting', 'forest-caretaker', ['LANTERN_KEEPER_KNOTS'],
        'Mara has kept the last returning courier\'s satchel in a sheltered cache. Recover the route ledger and leave a fresh lantern beside the marker.',
        [at('ledger', 'Recover the forest route ledger', 38, 158, 'Forest', 'The ledger records a failed rescue near the graveyard and a delivery that continued into the desert.'),
         at('lantern', 'Set a lantern at the southern marker', 43, 176, 'Forest', 'Mara\'s path now has a light. She can guide neighbours without pretending the missing courier has returned.')],
        'Mara offers forest berries for the next picnic. Take the ledger to Vince in Town when the coastal signal is also restored.'),
    quest('STONE_NAMES', 4, 'Three Names on the Stone', 'town-priest', ['LANTERN_COAST_SIGNAL', 'LANTERN_STILL_WAITING'],
        'Vince compares the coastal letters with Mara\'s ledger. Three names on a graveyard memorial belong to the rescue Rowan could not finish.',
        [at('names', 'Read the three names on the memorial', 47, 128, 'Graveyard', 'The stone names Elian, Sera and Tomas. Elian was Rowan\'s friend; the two couriers died trying to reopen the route.')],
        'Vince asks you to distinguish grief from blame. Rowan\'s silence followed a loss, rather than a quarrel with Town.'),
    quest('UNDELIVERED_LETTER', 4, 'A Letter Never Delivered', 'town-priest', ['LANTERN_STONE_NAMES'],
        'Elian left a letter in the old crypt archive. The graveyard entrance leads to the archive on the same main map.',
        [at('letter', 'Find Elian\'s letter in the crypt archive', 124, 112, 'Crypt archive',
            'Elian wrote: "If I do not return, let the road stay open. A light is useful because someone else can find it." The letter never reached Rowan.')],
        'Vince entrusts the letter to you. Decide how the neighbours should remember the rescue.',
        {choices: [pick('Light a public memorial so the loss is remembered together.', 'lantern:public-memorial', 'Vince will explain the names to visitors, with care rather than blame.'),
            pick('Keep the memorial quiet and carry the letter privately.', 'lantern:private-memorial', 'Vince keeps the personal words private. A small lantern still marks the loss.')]}),
    quest('MISSING_LIGHT', 4, 'A Light for the Missing', 'town-priest', ['LANTERN_UNDELIVERED_LETTER'],
        'The memorial is for the people who did not return. It is not a promise that restoring the road will undo their loss.',
        [at('memorial', 'Light the memorial lantern', 47, 128, 'Graveyard', 'A steady lantern marks the names. You can carry Elian\'s wish onward without making the memorial a spectacle.')],
        'Vince found Nessa\'s caravan address in the ledger. She is waiting in the southern desert with the last delivery.'),
    quest('EMPTY_LANTERNS', 5, 'A Trail of Empty Lanterns', 'desert-courier', ['LANTERN_MISSING_LIGHT'],
        'Nessa waits with a stranded caravan because the desert markers went dark. She refuses to leave the supplies or her companions behind.',
        [at('south', 'Check the southern desert marker', 50, 90, 'Desert', 'The first lantern is intact but has no relay power.'),
         at('north', 'Check the northern desert marker', 53, 72, 'Desert', 'The second lantern has the same fault. The shutdown came from the northern works.')],
        'Nessa now knows why the caravan stopped. Rowan\'s shutdown reached all the way into the desert.'),
    quest('LAST_DELIVERY', 5, 'The Last Delivery', 'desert-courier', ['LANTERN_EMPTY_LANTERNS'],
        'The caravan\'s dispatch box holds a regulator consignment and Rowan\'s final instruction. Nessa needs the box checked before she can safely send you north.',
        [at('dispatch', 'Recover the caravan dispatch box', 57, 88, 'Desert', 'The instruction reads: "Do not send anyone north. I will keep the flame myself." The regulator was left in a sealed northern store.')],
        'Nessa offers two ways to move the caravan\'s relay parts. Your choice changes the route you must inspect.',
        {choices: [pick('Take the sheltered detour for the tired travellers.', 'lantern:caravan-detour', 'Nessa chooses the eastern shelter and brings spare lantern oil.'),
            pick('Clear and mark the direct road.', 'lantern:caravan-direct', 'Nessa follows the central road and brings the heavier repair tools.')]}),
    quest('ROAD_WE_TAKE', 5, 'The Road We Take', 'desert-courier', ['LANTERN_LAST_DELIVERY'],
        'Nessa\'s caravan will follow the route you chose, so she needs your report from that route rather than a different marker.',
        [at('detour', 'Mark the sheltered eastern detour', 64, 77, 'Desert', 'The sheltered route is marked. Tired travellers can rest while their supplies continue north.', {when: 'lantern:caravan-detour'}),
         at('direct', 'Mark the central direct road', 44, 77, 'Desert', 'The central route is marked for the caravan and its heavier tools.', {when: 'lantern:caravan-direct'})],
        'Nessa dispatches the parts along your chosen road. Speak to the Northern Miner in Lavaland about the heat building at the relay.'),
    quest('HEAT_WITHOUT_LIGHT', 6, 'Heat Without Light', 'north-miner', ['LANTERN_ROAD_WE_TAKE'],
        'The miner stays near the northern workings because pressure is building while the route lamps stay dark. Orin needs a reading from the vent.',
        [at('vent', 'Read the northern relay vent', 91, 28, 'Lavaland', 'The flame is producing heat with nowhere to send it. Keeping the route closed made the pressure worse.')],
        'The miner sends you to Orin beside the vent. The missing regulator can safely distribute the flame.'),
    quest('MISSING_REGULATOR', 6, 'The Missing Regulator', 'north-technician', ['LANTERN_HEAT_WITHOUT_LIGHT'],
        'Orin recognises Nessa\'s dispatch seal. The regulator is in the old Boss store, reached by the northern Lavaland door; it needs no boss kill to recover.',
        [at('regulator', 'Recover the sealed regulator', 151, 65, 'Boss', 'The regulator bears Nessa\'s dispatch number. It was never delivered to Rowan.'),
         at('fit', 'Fit the regulator beside the vent', 91, 28, 'Lavaland', 'The pressure falls as the regulator distributes the heat. The flame is safe to reconnect.')],
        'Orin can work here because the regulator is fitted. Rowan\'s isolated watch is no longer necessary.'),
    quest('ROWAN_PROTECTED', 6, 'What Rowan Was Protecting', 'north-technician', ['LANTERN_MISSING_REGULATOR'],
        'Orin asks you to recover the keeper\'s service record before confronting Rowan. The north was dangerous, but the shutdown became its own danger.',
        [at('record', 'Read the northern service record', 101, 16, 'Lavaland', 'Rowan kept the flame running alone after the rescue. The record names the Gauntlet control room as his refuge.')],
        'Carry Elian\'s letter and the regulator report to the Gauntlet. Enter from northern Town; Rowan waits beside the old controls.'),
    quest('OLD_DEFENCES', 7, 'Through the Old Defences', 'lantern-keeper', ['LANTERN_ROWAN_PROTECTED'],
        'Rowan will listen after the old emergency controls are secured. You may use the isolation switches rather than fight your way through.',
        [at('switch', 'Secure the Gauntlet isolation switch', 67, 373, 'Gauntlet', 'The isolation switch is locked safely. The defences cannot disrupt the restored regulator.'),
         at('log', 'Check the keeper\'s control log', 73, 375, 'Gauntlet', 'The log confirms Rowan has not left his watch since the rescue. He has mistaken being alone for keeping everyone safe.')],
        'Rowan sets down the control log. He can hear you now because you showed that sharing the flame will not repeat the old accident.'),
    quest('KEEPER_CHOICE', 7, 'The Keeper\'s Choice', 'lantern-keeper', ['LANTERN_OLD_DEFENCES'],
        'Elian\'s letter asks Rowan to keep the road open. Show him the evidence from the communities before asking what he wants his life to become.',
        [at('letter', 'Place Elian\'s letter beside the keeper\'s controls', 68, 378, 'Gauntlet', 'Rowan reads the words slowly: "A light is useful because someone else can find it." He finally understands why you came.')],
        'Rowan asks whether to return as a keeper with help, or teach the next keepers and step away.',
        {choices: [pick('Return as keeper, with the communities sharing the watch.', 'lantern:rowan-keeper', 'Rowan agrees to keep the road with other people. He will send a place-setting to the long table.'),
            pick('Teach new keepers, then rest and choose your own future.', 'lantern:rowan-handover', 'Rowan entrusts the controls to Orin and Mara. He asks for a quiet place at the long table.')]}),
    quest('LIGHT_SHARED', 7, 'Light Shared Again', 'lantern-keeper', ['LANTERN_KEEPER_CHOICE'],
        'The controls are ready, the regulator is fitted, and Rowan has chosen a future. Restore the network while keeping every community\'s lantern in service.',
        [at('controls', 'Reconnect the lantern road', 69, 378, 'Gauntlet', 'The lamps answer from the coast, forest, memorial and desert. Each community has a share of the flame now.')],
        'The road is open because you carried evidence between people who had stopped hearing from each other. Return to Bstrat in Town to send new invitations.'),
    quest('RETURNED_INVITATIONS', 8, 'The Invitations Returned', 'town-neighbour', ['LANTERN_LIGHT_SHARED'],
        'Bstrat has prepared invitations along the restored road. Deliver them to the communities that helped you, so they know this invitation is meant for them.',
        [at('coast', 'Deliver the coastal invitation to Jimi', 76, 293, 'Beach', 'Jimi recognises your repaired signal and promises sea-salt bread.'),
         at('forest', 'Deliver the forest invitation to Mara', 58, 176, 'Forest', 'Mara recognises the relit trail and promises berries from the forest.'),
         at('desert', 'Deliver the caravan invitation to Nessa', 47, 94, 'Desert', 'Nessa will bring the oil or tools from the route you chose.'),
         at('north', 'Deliver the northern invitation to Orin', 97, 29, 'Lavaland', 'Orin can leave the relay for a while because the regulator now shares its load.')],
        'Bstrat has replies from every region. Adam is gathering the contributions at the Party Beach long table.'),
    quest('BRING_WITH_US', 8, 'What We Bring With Us', 'town-gardener', ['LANTERN_RETURNED_INVITATIONS'],
        'Adam remembers how you solved the basket problem. This time each region has something to share at the Party Beach gathering.',
        [at('table', 'Arrange the contributions at the long table', 40, 450, 'Party beach', 'Bread, forest berries and desert lanterns fill the long table. There is room for the northern keepers and the neighbours who helped the watch.')],
        'Adam sends word to Wild Will at Party Beach. The long table is ready, and Rowan\'s place is no longer forgotten.'),
    quest('LONG_TABLE', 8, 'The Long Table', 'party-wildwill', ['LANTERN_BRING_WITH_US'],
        'Wild Will welcomes the gathering without pretending the missing crew or Elian have come back. This picnic makes room for both new company and old memories.',
        [at('gather', 'Join the lanterns at the long table', 40, 450, 'Party beach', 'The table is set for every community. Your quiet or musical invitation, the memorial and Rowan\'s future are all remembered.')],
        'The Lantern Road remains open. You can revisit the people you helped or finish optional stories; your choices stay with this character.'),

    quest('WATCH_RELIEF', 2, 'The Watch\'s Night Off: A Relief Patrol', 'town-watch', [I],
        'The watch could only stay briefly at the first picnic because nobody covered the gate. Find a neighbour willing to take a relief round.',
        [at('relief', 'Ask at the eastern gate\'s relief post', 73, 201, 'Town', 'A relief volunteer agrees to cover the gate when the watch attends the long table.')],
        'The watch can plan a full evening off once the relief route is prepared.', {optional: true}),
    quest('WATCH_ROUND', 3, 'The Watch\'s Night Off: Mark the Round', 'town-watch', ['LANTERN_WATCH_RELIEF'],
        'The volunteer needs a safe, clear route rather than a promise that nothing will happen.',
        [at('market', 'Mark the market relief stop', 43, 210, 'Town', 'The market stop is marked for the relief patrol.'),
         at('forest', 'Mark the southern forest relief stop', 40, 190, 'Forest', 'The southern forest stop connects the relief route to the gate.')],
        'The relief volunteer knows exactly where the watch usually checks.', {optional: true}),
    quest('WATCH_INVITED', 8, 'The Watch\'s Night Off: A Whole Evening', 'town-watch', ['LANTERN_WATCH_ROUND', 'LANTERN_LIGHT_SHARED'],
        'With the road restored and the relief route marked, the watch can accept a whole evening at the long table.',
        [at('rota', 'Leave the relief rota at the gate', 73, 201, 'Town', 'The volunteer takes the rota. The watch can attend without abandoning the gate.')],
        'The watch will stay for the whole gathering because you arranged real relief.', {optional: true}),
    quest('MISSING_MESSAGES', 4, 'Those Who Couldn\'t Come: Messages', 'town-priest', ['LANTERN_MISSING_LIGHT'],
        'Vince asks for messages from families along the road. Their absence deserves an explanation rather than an empty place nobody mentions.',
        [at('family', 'Collect the graveyard family\'s message', 46, 120, 'Graveyard', 'The family asks for a lantern beside the table, without speeches about their private grief.')],
        'Vince keeps the message with care and asks you to check the desert family next.', {optional: true}),
    quest('MISSING_KEEPSAKES', 5, 'Those Who Couldn\'t Come: Keepsakes', 'desert-courier', ['LANTERN_MISSING_MESSAGES', 'LANTERN_ROAD_WE_TAKE'],
        'A caravan family cannot travel to the gathering. Nessa asks you to carry a keepsake rather than pressure them to attend.',
        [at('keepsake', 'Collect the caravan\'s small keepsake lantern', 57, 88, 'Desert', 'The family sends a small lantern and thanks you for respecting their decision to stay.')],
        'Nessa packs the keepsake safely. Vince can help you make a place for it at the table.', {optional: true}),
    quest('MISSING_PLACES', 8, 'Those Who Couldn\'t Come: Places Kept', 'town-priest', ['LANTERN_MISSING_KEEPSAKES', 'LANTERN_LIGHT_SHARED'],
        'The messages and keepsakes explain the empty places. Honour those wishes at the table instead of treating attendance as the only kind of belonging.',
        [at('place', 'Set the keepsake lantern at the long table', 42, 450, 'Party beach', 'A small lantern keeps a place for the families. Their private messages remain private.')],
        'The gathering has a quiet place for the people who could not come.', {optional: true}),
    quest('WILL_SHORE', 2, 'Wild Will\'s Place: The Shore', 'party-wildwill', [I],
        'Wild Will remembers the sea creature that took his crew. He will consider the gathering if the approach feels safe for visiting neighbours.',
        [at('shore', 'Mark the Party Beach landing', 47, 439, 'Party beach', 'The landing is clearly marked. Visiting neighbours can find a safe place to arrive.')],
        'Wild Will appreciates the practical help. A keepsake from the old beach may help him explain why company still feels difficult.', {optional: true}),
    quest('WILL_KEEPSAKE', 4, 'Wild Will\'s Place: The Crew\'s Keepsake', 'party-wildwill', ['LANTERN_WILL_SHORE'],
        'Will asks for a recovered keepsake from the shore. He wants to remember the crew without making new neighbours carry the blame for his loneliness.',
        [at('keepsake', 'Recover the crew\'s weathered cup', 68, 288, 'Beach', 'The cup carries the crew\'s mark. It is a keepsake, not a promise that the sea will give them back.')],
        'Will agrees to save a place for new company while remembering his crew.', {optional: true}),
    quest('WILL_NEIGHBOUR', 8, 'Wild Will\'s Place: A New Neighbour', 'party-wildwill', ['LANTERN_WILL_KEEPSAKE', 'LANTERN_LIGHT_SHARED'],
        'Will wants Jimi to know that the long table has room for him too. Carry a personal invitation back along the coast.',
        [at('invite', 'Deliver Wild Will\'s invitation to Jimi', 76, 293, 'Beach', 'Jimi accepts the invitation. Will asked him directly, rather than waiting for him to guess.')],
        'Will and Jimi will share a place at the gathering because you carried that invitation.', {optional: true}),
    quest('SPARK_TRAINING', 6, 'The Last Sparks: Control Practice', 'north-technician', ['LANTERN_MISSING_REGULATOR'],
        'Orin has an optional precision tool in Megamag. Practise the control sequence at the Fight Night practice post first; PvP is not required.',
        [at('practice', 'Practise the relay control sequence', 20, 330, 'Fight night', 'The practice controls click safely into place. You can now identify the precision tool.')],
        'Orin trusts you with the optional Megamag tool recovery. It improves the lanterns but is not required to finish the story.', {optional: true}),
    quest('SPARK_TOOL', 7, 'The Last Sparks: A Golden Light', 'north-technician', ['LANTERN_SPARK_TRAINING'],
        'The precision tool is in Megamag, reached through the existing northern Lavaland door. Its guarded route is optional.',
        [at('tool', 'Recover the precision tool from Megamag', 155, 166, 'Megamag', 'The recovered tool lets Orin polish a golden lantern for the long table.')],
        'Orin sends a golden lantern to the gathering as thanks. The main road was already safe without this tool.', {optional: true})
];
for (const q of quests) {
    const npc = npcs.find(npc => npc.key === q.npcKey);
    q.npc = Types.getKindFromString(npc.kind);
    q.requiredQuest = q.requiredQuests[0];
    q.startText = q.reason;
    q.endText = q.conclusion;
}
const objectiveFlag = (q, objective, count) => 'lantern:objective:' + q.id + ':' + objective.key + (count ? ':' + count : '');
module.exports = {version: 1, chapters, npcs, quests, objectiveFlag};
