Types = require("../../../shared/js/gametypes");
quests = [        
    {
        id: "COB_COLLECT_LOGS",
        name: "Maintaining the campfire",
        startText: "We are running out of wood! Find 20 logs to keep the fire going.",
        endText: "Thanks to you it will not be dark here tonight!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.COBLUMBERJACK,
        target: Types.Entities.COBLOG,
        requiredLevel: 7,
        amount: 20,
        level: 9,
        medal: Types.Medals.TREE
    },
    {
        id: "COB_BLUE_SLIMES",
        name: "Finding the lucky clover",
        startText: "The blue slimes stole my lucky clover! Kill 40 of them, get it back!",
        endText: "Thank you! It weren't the blue slimes after all...",
        eventType: "KILL_MOB",
        npc: Types.Entities.COBHILLSNPC,
        target: Types.Entities.COBSLIMEBLUE,
        amount: 40,
        level: 2,
        medal: Types.Medals.SKULL
    },
    {
        id: "COB_YELLOW_SLIMES",
        name: "Finding the lucky clover again",
        startText: "My bad! It was the yellow ones! Kill 40 of them, they must have the clover!",
        endText: "Well, at least it's less slimes here!",
        eventType: "KILL_MOB",
        npc: Types.Entities.COBHILLSNPC,
        target: Types.Entities.COBSLIMEYELLOW,
        amount: 40,
        requiredQuest: "COB_BLUE_SLIMES",
        level: 4,
        medal: Types.Medals.SKULL
    },
    {
        id: "COB_RED_SLIMES",
        name: "Still finding the lucky clover",
        startText: "Yellow, red... it's all the same! Kill 60 red ones, one of them has it!",
        endText: "Where's the clover? Will we ever find it again?",
        eventType: "KILL_MOB",
        npc: Types.Entities.COBHILLSNPC,
        target: Types.Entities.COBSLIMERED,
        amount: 60,
        requiredQuest: "COB_YELLOW_SLIMES",
        level: 6,
        medal: Types.Medals.SKULL
    },
    {
        id: "COB_RAINBOW_SLIME",
        name: "Finally finding the lucky clover",
        startText: "Now I remember! It was ALL OF THEM! Get the rainbow slime!",
        endText: "Thank you so much! This clover means a lot to me.",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.COBHILLSNPC,
        target: Types.Entities.COBCLOVER,
        amount: 1,
        requiredQuest: "COB_RED_SLIMES",
        level: 8,
        medal: Types.Medals.SKULL
    },
    {
        id: "COB_MISSING_EGGS",
        name: "Missing eggs",
        startText: ["Our eggs have been mysteriously disappearing.",
        "Could you investigate what's happening?"],
        questLogText: "Figure out what happened to the missing eggs.",
        endText: "Good find!",
        eventType: "KILL_MOB",
        npc: Types.Entities.COBJOHNNY,
        target: Types.Entities.COBDIRT,
        requiredLevel: 9,
        amount: 1,
        level: 6,
        medal: Types.Medals.CAVE
    },
    {
        id: "COB_RETRIEVE_EGGS",
        name: "Retrieve the stolen eggs",
        startText: ["Because of the Coblins we are running short on eggs!",
        "Can you retrieve them from the hidden cave?"],
        questLogText: "Retrieve 50 stolen eggs",
        endText: "Good job!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.COBJOHNNY,
        target: Types.Entities.COBEGG,
        requiredQuest: "COB_MISSING_EGGS",
        amount: 50,
        level: 12,
        medal: Types.Medals.TREE
    },
    {
        id: "COB_KILL_COBLINS",
        name: "Fending off the Coblins",
        startText: ["Coblins invaded our farm last night.",
        "Could you kill 40 of them to send a clear message?"],
        questLogText: "Kill 40 Coblins",
        endText: "Thank you! That will show them!",
        eventType: "KILL_MOB",
        npc: Types.Entities.COBJOHNNY,
        target: Types.Entities.COBCOBLIN,
        requiredQuest: "COB_MISSING_EGGS",
        amount: 40,
        level: 12,
        medal: Types.Medals.SKULL
    },
    {
        id: "COB_KILL_COBANES",
        name: "Scaring off the Cobanes",
        startText: ["Those Cobanes won't learn!",
        "They're causing chaos amongst the animals...",
        "Kill 40 of them, that will teach them a lesson!"],
        questLogText: "Kill 40 Cobanes",
        endText: "Let's hope they won't come back!",
        eventType: "KILL_MOB",
        npc: Types.Entities.COBJOHNNY,
        target: Types.Entities.COBCOBANE,
        requiredQuest: "COB_KILL_COBLINS",
        amount: 40,
        level: 14,
        medal: Types.Medals.SKULL
    },
    {
        id: "COB_KILL_COBOGRE",
        name: "Defeat the Ogre Leader",
        startText: ["Their ogre leader is orchestrating all this.",
        "He lurks deep in the cave.",
        "Can you take him down?"],
        questLogText: "Kill the Ogre Leader",
        endText: "The animals are safe thanks to you!",
        eventType: "KILL_MOB",
        npc: Types.Entities.COBJOHNNY,
        target: Types.Entities.COBOGRE,
        requiredQuest: "COB_KILL_COBANES",
        amount: 1,
        level: 15,
        medal: Types.Medals.SKULL
    }
]

exports.quests = quests;