Types = require("../../../shared/js/gametypes");
quests = [
    {
        id: "KINGFROGGY_QUEST_1",
        name: "The King's Blue Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 blue balloon dogs to see if that helps."],
        endText: "Thanks for your help popping those blue balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGB,
        amount: 100,
        level: 1,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_2",
        name: "The King's Yellow Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 yellow balloon dogs."],
        endText: "Thanks for your help popping those yellow balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGY,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_1",
        level: 4,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_3",
        name: "The King's Green Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!", 
        "The King has requested that you pop 100 green balloon dogs."],
        endText: "Thanks for your help popping those green balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGG,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_2",
        level: 6,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_4",
        name: "The King's Aqua Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 aqua balloon dogs."],
        endText: "Thanks for your help popping those aqua balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGA,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_3",
        level: 8,
        xp: 30000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_5",
        name: "The King's Violet Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 violet balloon dogs."],
        endText: "Thanks for your help popping those violet balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGV,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_4",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_6",
        name: "The King's Pink Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 pink balloon dogs."],
        endText: "Thanks for your help popping those pink balloon dogs! It looks like we're still floating higher and higher though. I bet that menacing looking hotdog has a lot of helium in it.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGP,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_5",
        level: 12,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_7",
        name: "The King's Red Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 5 red balloon hotdogs."],
        endText: "Thanks for your help popping those red balloon hotdogs! It looks like we're still floating higher and higher though. Hmmm, I thought for sure that would do it. We have one more chance...",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONHOTDOGR,
        amount: 5,
        requiredQuest: "KINGFROGGY_QUEST_6",
        level: 20,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_8",
        name: "The King's Orange Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 1 orange balloon giraffe."],
        endText: "Thanks for your help popping all of those balloon animals! You did it!! Thank you! It looks like we're going to stay in this stratosphere for now!",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONGIRAFFEO,
        amount: 1,
        requiredQuest: "KINGFROGGY_QUEST_7",
        level: 20,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_9",
        name: "The King's Mysterious Map Request",
        startText: ["Every now and then I see a mysterious map pop up around here...",
        "I wonder what would happen if you collected them? The next time you see one hang on to it!"],
        endText: "Wow, great job collecting all of those maps! What an interesting number...Keep your eyes peeled for some sort of secret portal or something...",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.M88NMAP,
        amount: 741,
        requiredQuest: "KINGFROGGY_QUEST_8",
        level: 30,
        xp: 300000,
        medal: Types.Medals.SKULL
    },
    {
        id: "GAMER_QUEST_1",
        name: "The Gamer's Vintage Gameboy Request",
        startText: ["I'm pretty sure I've seen some sweet vintage Gameboys around here...",
        "Can you help me find as many as you can? There might be some cool old school games on them!"],
        endText: "Wow, great job collecting all of those Gameboys! Looks like they don't have any batteries in them though...",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.GAMEBOY,
        amount: 69,
        level: 10,
        xp: 69420,
        medal: Types.Medals.SKULL
    },
    {
        id: "GAMER_QUEST_2",
        name: "The Gamer's Battery Request",
        startText: ["I've seen some batteries around here somewhere...we're gonna need them if we wanna play these Gameboys...",
        "Can you help me find as many as you can? Hopefully they're all charged up!"],
        endText: "Wow, great job collecting all of those batteries! Power to the players and to the collectors ;)",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.BATTERY,
        amount: 69,
        requiredQuest: "GAMER_QUEST_1",
        level: 20,
        xp: 69420,
        medal: Types.Medals.SKULL
    },
    {
        id: "GAMER_QUEST_3",
        name: "The Gamer's Hard Wallet Request",
        startText: ["Did you know the safest place to store your crypto is on a hard wallet? I know I've seen some around here every once in a while...",
        "Can you help me find as many as you can? Then we can make sure to keep our investments safe!"],
        endText: "Wow, great job collecting all of those hard wallets! Power to the investors ;)",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.HARDWALLET,
        amount: 69,
        requiredQuest: "GAMER_QUEST_2",
        level: 30,
        xp: 69420,
        medal: Types.Medals.SKULL
    },
    {
        id: "GAMER_QUEST_4",
        name: "The Gamer's 3D Movie Glasses Request",
        startText: ["I heard if you have some special 3D movie glasses you can actually see which shares are synthetic...Sounds weird, but it's worth a try!",
        "Can you help me find as many as you can? Then we can try them on and see if the rumor is true!"],
        endText: "Wow, great job collecting all of those 3D movie glasses! Did you try them on yet?? Some of the shares have a little purple circle on them now!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.MOVIEGLASSES,
        amount: 69,
        requiredQuest: "GAMER_QUEST_3",
        level: 40,
        xp: 69420,
        medal: Types.Medals.SKULL
    },
    {
        id: "CHEF_QUEST_1",
        name: "The Chef's Steak Dinner Request",
        startText: ["I'm preparing a spectacular dinner party...do you want to help me find the ingredients?",
        "It's not going to be easy but I'll gladly pay you 420k xp for your time!",
        "The first thing we're going to need is the main course...steak! Can you help me find 20 yummy steaks?"],
        endText: "Wow, great job collecting all of those delicious steaks! How about we have baked potatoes for the side?",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NSTEAK,
        amount: 20,
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "CHEF_QUEST_2",
        name: "The Chef's Baked Potato Request",
        startText: ["I can't think of a better side to go with steak than a baked potato!",
        "Can you help me find 20 potatoes?"],
        endText: "Nice, great job collecting all of those potatoes! I think a nice tossed salad would go well with these!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NPOTATO,
        amount: 20,
        requiredQuest: "CHEF_QUEST_1",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "CHEF_QUEST_3",
        name: "The Chef's Tossed Salad Request",
        startText: ["We should probably make sure to be healthy and have our greens with dinner!",
        "Can you help me find 20 salads?"],
        endText: "Awesome, great job collecting all of those salads! How about we have some ice cold brewskis with dinner?",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NSALAD,
        amount: 20,
        requiredQuest: "CHEF_QUEST_2",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "CHEF_QUEST_4",
        name: "The Chef's Ice Cold Brewski Request",
        startText: ["We're going to need something to wash all this food down with, how about we celebrate with some brewskis?!",
        "Can you help me find 20 ice cold brewskis?"],
        endText: "Cheers! Great job collecting all of those brewskis! How does boysenberry pie sound for dessert?",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NBREWSKI,
        amount: 20,
        requiredQuest: "CHEF_QUEST_3",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "CHEF_QUEST_5",
        name: "The Chef's Boysenberry Pie Request",
        startText: ["And for our final course, I think boysenberry pie should hit the spot!",
        "Can you help me find 20 slices of pie?"],
        endText: ["Ayyy! Great job collecting all of those slices of pie!",
        "Thanks so much for helping put this amazing dinner together!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NPIE,
        amount: 20,
        requiredQuest: "CHEF_QUEST_4",
        level: 10,
        xp: 120000,
        medal: Types.Medals.SKULL
    },
    {
        id: "CHEF_QUEST_6",
        name: "The Chef's Dinner Bell Request",
        startText: ["Now we just need to let everyone know it's dinner time!",
        "Can you find a dinner bell for me?"],
        endText: ["Amazing, thanks mate!",
        "Dinner is served!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NDINNERBELL,
        amount: 1,
        requiredQuest: "CHEF_QUEST_5",
        level: 10,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "FARMERS_QUEST_1",
        name: "Farmer Joe's Shovel Request",
        startText: ["Sheesh...I'm exhausted. The only garden tool we have so far is a hand trowel!",
        "If you can help me find some new supplies to plant another set of crops I'll hook you up with some xp!",
        "The first thing we're going to need is bigger shovel! Can you help me find 2 large shovels?"],
        endText: "Thanks so much for finding those shovels! Next we're going to need lots and lots of seeds!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN13,
        target: Types.Entities.M88NSHOVEL,
        amount: 2,
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL
    },
    {
        id: "FARMERS_QUEST_2",
        name: "Farmer Joe's Seed Request",
        startText: ["Okay, while we digging can you keep your eyes open for some seeds?",
        "A couple months ago we found some that had washed up by the shore! See if you can find like 20 bags of seeds."],
        endText: ["Thanks so much for finding those seeds! That'll keep us busy for a while.",
        "Now we just need a couple of watering cans!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN13,
        target: Types.Entities.M88NSEEDS,
        amount: 20,
        requiredQuest: "FARMERS_QUEST_1",
        level: 10,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "FARMERS_QUEST_3",
        name: "Farmer Joe's Watering Can Request",
        startText: ["Sweet! We're going to start planting some of these seeds.",
        "We're going to need to water them pretty quickly though.",
        "Can you please find us 2 watering cans?"],
        endText: ["Perfect, thanks for finding those watering cans!",
        "The last thing we're going to need are some sacks to store our harvest in!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN13,
        target: Types.Entities.M88NWATERCAN,
        amount: 2,
        requiredQuest: "FARMERS_QUEST_2",
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL
    },
    {
        id: "FARMERS_QUEST_4",
        name: "Farmer Joe's Harvest Sack Request",
        startText: ["Now we're cooking! I think the last thing we need is a sack of some sort to put our harvested crops in.",
        "Can you please find us 2 burlap sacks?"],
        endText: ["Amazing, thank you so much for finding these supplies for us, this will make our life so much easier!",
        "We're happy to be your hook up while you're visiting The Nexus! Anytime you need uh...tomatoes you know where to find us!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN13,
        target: Types.Entities.M88NSACK,
        amount: 2,
        requiredQuest: "FARMERS_QUEST_3",
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL
    },
    {
        id: "MAILMAN_QUEST_1",
        name: "The Mail Man's Mail Request",
        startText: ["So, um, I have a request for some help if you have any extra time...",
        "I set my mail bag down and accidentally let a bunch of envelopes blow away, can you help me find 20 pieces of mail?"],
        endText: ["Oh, thank goodness! You're amazing! Thanks for finding those for me!",
        "While I'm delivering these do you think you can help me collect some packages that need to be brought to the post office?"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN15,
        target: Types.Entities.M88NMAIL,
        amount: 20,
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "MAILMAN_QUEST_2",
        name: "The Mail Man's Package Request",
        startText: ["You have a great eye and you're saving me lots of time, would you mind helping me find some packages too?",
        "There are 20 packages around here somewhere that I need to get back to the post office. After you help me I have a cool surpise for you!"],
        endText: ["Thank you so much! If you ever want to work for the post office here in The Nexus I'll put in a good word for you!",
        "There is a secret door somewhere in Paradise Point that I unlocked for you... Find it and there is a yacht boarding ticket just for you!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN15,
        target: Types.Entities.M88NPACKAGE,
        amount: 20,
        requiredQuest: "MAILMAN_QUEST_1",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "MAILMAN_QUEST_3",
        name: "The Mail Man's Mysterious Ticket Request",
        startText: ["You know that cool yacht over there? You need a special ticket to board...",
        "Find a secret hidden door somewhere in Paradise Point and there's a boarding ticket waiting for you!"],
        endText: ["Have fun on the Sun Chaser! I hear there is some special fishing on it for the apes!",
        "And if you're able to find the golden ticket there is a cool champagne lounge on the yacht too..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN15,
        target: Types.Entities.M88NTICKET,
        amount: 1,
        requiredQuest: "MAILMAN_QUEST_2",
        level: 10,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "EXPLORER_QUEST_1",
        name: "The Explorer's Fly Request",
        startText: ["There are so many cool little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "Right now I'm looking for these weird little flies, can you help me find 10 of them?"],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NFLY,
        amount: 10,
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "EXPLORER_QUEST_2",
        name: "The Explorer's June Bug Request",
        startText: ["There are so many interesting bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "Next, I'm looking for these odd little green june bugs, can you help me find 10 of them?"],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NJUNEBUG,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_1",
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL
    },
    {
        id: "EXPLORER_QUEST_3",
        name: "The Explorer's Dung Beetle Request",
        startText: ["There are so many cool little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "Next, I'm looking for these smelly little dung beetles, can you help me find 10 of them?"],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NDUNGBEETLE,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_2",
        level: 10,
        xp: 30000,
        medal: Types.Medals.SKULL
    },
    {
        id: "EXPLORER_QUEST_4",
        name: "The Explorer's Stick Bug Request",
        startText: ["There are so many odd little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "Next, I'm looking for these skinny little stick bugs, can you help me find 10 of them?"],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NSTICKBUG,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_3",
        level: 10,
        xp: 40000,
        medal: Types.Medals.SKULL
    },
    {
        id: "EXPLORER_QUEST_5",
        name: "The Explorer's Snail Request",
        startText: ["There are so many weird little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "Next, I'm looking for these slimey little snails, can you help me find 10 of them?"],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NSNAIL,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_4",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "EXPLORER_QUEST_6",
        name: "The Explorer's Butterfly Request",
        startText: ["There are so many weird little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "For my last request, I'm looking for these magical little butterflies.",
        "If you help me find 10 of them my mission will be complete!",
        "As a thank you for all of your help I'd love to give you a really special item that you'll find handy soon...",
        "There's a hidden door around Paradise Point somewhere. If you find it there are a pair of binoculars waiting for you!"],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NBUTTERFLY,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_5",
        level: 10,
        xp: 69000,
        medal: Types.Medals.SKULL
    },
    {
        id: "FISHERMAN_QUEST_1",
        name: "The Fisherman's Fishing Request",
        startText: ["Did you know you there are TONS of different fish that you can catch in this ocean?",
        "You'll need a fishing pole first though. Wanna borrow one of mine to try it out before you buy your own?",
        "Grab that fishing pole right there and I'll drop a 24 hour rental pole into your inventory!"],
        endText: ["Happy fishing friend!!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN16,
        target: Types.Entities.M88NFISHINGPOLE,
        amount: 1,
        level: 10,
        xp: 1000,
        medal: Types.Medals.SKULL,
        rental: "0xd3894a9a6f325cd660916340ba5e040ca17b53504a7c7860d61329ac013e5d84"
    },
    {
        id: "FISHERMAN_QUEST_2",
        name: "The Fisherman's Worm Request",
        startText: ["If I had some nice plump worms I'd probably be able to catch some bigger fish...",
        "Do you think you could find me like 20 worms?"],
        endText: ["Thanks for the new bait! It's working like a charm! Happy fishing friend!!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN16,
        target: Types.Entities.M88NWORM,
        amount: 20,
        requiredQuest: "FISHERMAN_QUEST_1",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "CLASSYLADY_QUEST_1",
        name: "The Classy Lady's Earring Request",
        startText: ["Some of my luggage got misplaced and I can't go to the dinner party without my jewelry...",
        "Can you please find my gold earrings?"],
        endText: ["Oh thank you! I love these earrings!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN4,
        target: Types.Entities.M88NGOLDEARRINGS,
        amount: 1,
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "CLASSYLADY_QUEST_2",
        name: "The Classy Lady's Diamond Necklace Request",
        startText: ["The next piece of jewelry that I'm missing is my Diamond Necklace...",
        "Can you please keep your eyes open for that too?"],
        endText: ["Oh my goodness thank you so much! This was my grandmother's necklace!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN4,
        target: Types.Entities.M88NDIAMONDNECKLACE,
        amount: 1,
        requiredQuest: "CLASSYLADY_QUEST_1",
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "CLASSYLADY_QUEST_3",
        name: "The Classy Lady's Diamond Ring Request",
        startText: ["I lost my wedding ring! My husband will be so mad if he finds out...",
        "Can you please try to find my diamond ring? And make sure you keep this on the downlow!"],
        endText: ["Oh, my hero! Thank you so much! Do you know how much this thing is worth?!",
        "Please accept this 50,000 bonus xp as a reward for finding it!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN4,
        target: Types.Entities.M88NDIAMONDRING,
        amount: 1,
        requiredQuest: "CLASSYLADY_QUEST_2",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "CLASSYLADY_QUEST_4",
        name: "The Classy Lady's Gold Tiara Request",
        startText: ["Okay, the last big piece of jewelry I am missing is my gold tiara. I won it when I was crowned Miss Nexus...",
        "Please look all over to help me find this! If you are able to find it I have a really special reward for you..."],
        endText: ["Yay! I feel complete again and now I can go to that dinner party!",
        "There is a secret door somewhere in The Nexus that I have unlocked for you!",
        "Find it and there is a golden compass waiting beyond it. It will come in handy soon, trust me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN4,
        target: Types.Entities.M88NGOLDTIARA,
        amount: 1,
        requiredQuest: "CLASSYLADY_QUEST_3",
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL
    },
    {
        id: "FOREMAN_QUEST_1",
        name: "The Foreman's Hard Hat Request",
        startText: ["I need to add more men to my crew if I want to get this finished anytime soon...",
        "The first thing we're going to need are some hard hats to make sure everyone is safe.",
        "Can you look around and see if you can find me 10 hard hats?"],
        endText: ["Great job, thank you!",
        "Now we're going to need to find some work gloves!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN31,
        target: Types.Entities.M88NHARDHAT,
        amount: 10,
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL
    },
    {
        id: "FOREMAN_QUEST_2",
        name: "The Foreman's Work Gloves Request",
        startText: ["Next, my men are going to need some work gloves...",
        "Each worker is going to need a pair of them.",
        "Can you look around and see if you can find me 20 work gloves?"],
        endText: ["Great job, thank you!",
        "Now we're going to need to find some blueprints!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN31,
        target: Types.Entities.M88NWORKGLOVES,
        amount: 20,
        requiredQuest: "FOREMAN_QUEST_1",
        level: 10,
        xp: 30000,
        medal: Types.Medals.SKULL
    },
    {
        id: "FOREMAN_QUEST_3",
        name: "The Foreman's Blueprint Request",
        startText: ["Finally, we're going to need some blueprints to follow along to...",
        "Each worker is going to need their own copy.",
        "Can you look around and see if you can find me 10 blueprints?"],
        endText: ["Great job, thank you!",
        "Now we can get cracking on expanding Paradise Point!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN31,
        target: Types.Entities.M88NBLUEPRINT,
        amount: 10,
        requiredQuest: "FOREMAN_QUEST_2",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "GREASER_QUEST_1",
        name: "The Greaser's Red Rose Request",
        startText: ["See that girl in the poodle skirt over there?",
        "I'm real keen on her and want to go steady...",
        "I gotta do something to get her attention though.",
        "Can you help me find a dozen red roses to give her?"],
        endText: ["Ayyy, thank you!",
        "I think she'd appreciate a nice promise ring too!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN32,
        target: Types.Entities.M88NROSE,
        amount: 12,
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL
    },
    {
        id: "GREASER_QUEST_2",
        name: "The Greaser's Promise Ring Request",
        startText: ["Those flowers are definitely going to get her attention!",
        "If I want everyone to know she's my gal she's gonna need a promise ring too...",
        "I know she likes rubies...Do you think you could help me find something nice?",
        "That would be the bee's knees!"],
        endText: ["Ayyy, thank you so much! Wish me luck!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN32,
        target: Types.Entities.M88NRUBYRING,
        amount: 1,
        requiredQuest: "GREASER_QUEST_1",
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "BUSHGUY_QUEST_1",
        name: "The Bush Guy's Clean Undies Request",
        startText: ["Pssst...Hey uh, this is sort of awkward...",
        "I was skinny dipping last night and my clothes went out with the tide.",
        "I'm hiding in this bush now because I'm naked!",
        "Can you help me find my clothes so I can get out of here?",
        "First, I'm going to need a pair of clean undies."],
        endText: ["Oh wow, thank you so much! How about a pair of pants?"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.M88NBUSHGUY,
        target: Types.Entities.M88NCLEANUNDIES,
        amount: 1,
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "BUSHGUY_QUEST_2",
        name: "The Bush Guy's Pants Request",
        startText: ["Okay, at least I have some clean undies now! Thank you!",
        "Do you think you can find me a pair of pants to wear too?"],
        endText: ["Haha, sweet! You're a savior! One last thing? How about a t-shirt now?"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.M88NBUSHGUY,
        target: Types.Entities.M88NPANTS,
        amount: 1,
        requiredQuest: "BUSHGUY_QUEST_1",
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "BUSHGUY_QUEST_3",
        name: "The Bush Guy's T-Shirt Request",
        startText: ["Wow, I'm so lucky you came around! Thank you for your help!",
        "Would you do me one last favor and find me a t-shirt to wear so I can get out of here?"],
        endText: ["Haha, amazing! Thank you so much for your help friend!",
        "Believe it or not I'm actually getting use to it in here! I think I might stick around for a little longer..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.M88NBUSHGUY,
        target: Types.Entities.M88NTSHIRT,
        amount: 1,
        requiredQuest: "BUSHGUY_QUEST_2",
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "BUTLERS_QUEST_1",
        name: "The Butler's Compass Request",
        startText: ["That portal on the far left will bring you to a hidden island!",
        "But you're going to need a special compass to navigate yourself there..."],
        endText: ["Heyyyy, you found the compass! Now you can go ahead and checkout the island. Have fun!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN29,
        target: Types.Entities.M88NCOMPASS,
        amount: 1,
        level: 10,
        xp: 100000,
        medal: Types.Medals.SKULL
    }
]

exports.quests = quests;