Types = require("../../../shared/js/gametypes");
quests = [
    {
        id: "KINGFROGGY_QUEST_1",
        name: "The King's Blue Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 blue balloon dogs to see if that helps."],
        endText: "Thanks for your help popping those blue balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGB,
        amount: 100,
        level: 1,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_2",
        name: "The King's Yellow Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 yellow balloon dogs."],
        endText: "Thanks for your help popping those yellow balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGY,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_1",
        level: 4,
        xp: 20000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_3",
        name: "The King's Green Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!", 
        "The King has requested that you pop 100 green balloon dogs."],
        endText: "Thanks for your help popping those green balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGG,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_2",
        level: 6,
        xp: 30000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_4",
        name: "The King's Aqua Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 aqua balloon dogs."],
        endText: "Thanks for your help popping those aqua balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGA,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_3",
        level: 8,
        xp: 40000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_5",
        name: "The King's Violet Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 violet balloon dogs."],
        endText: "Thanks for your help popping those violet balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGV,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_4",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_6",
        name: "The King's Pink Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 pink balloon dogs."],
        endText: "Thanks for your help popping those pink balloon dogs! It looks like we're still floating higher and higher though. I bet that menacing looking hotdog has a lot of helium in it.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGP,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_5",
        level: 12,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_7",
        name: "The King's Red Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 5 red balloon hotdogs."],
        endText: "Thanks for your help popping those red balloon hotdogs! It looks like we're still floating higher and higher though. Hmmm, I thought for sure that would do it. We have one more chance...",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONHOTDOGR,
        amount: 5,
        requiredQuest: "KINGFROGGY_QUEST_6",
        level: 20,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_8",
        name: "The King's Orange Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 1 orange balloon giraffe."],
        endText: "Thanks for your help popping all of those balloon animals! You did it!! Thank you! It looks like we're going to stay in this stratosphere for now!",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONGIRAFFEO,
        amount: 1,
        requiredQuest: "KINGFROGGY_QUEST_7",
        level: 20,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_9",
        name: "The King's Mysterious Map Request",
        startText: ["Every now and then I see a mysterious map pop up around here...",
        "I wonder what would happen if you collected them? The next time you see one hang on to it!"],
        endText: "Wow, great job collecting all of those maps! What an interesting number...Keep your eyes peeled for some sort of secret portal or something...",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.M88NMAP,
        amount: 741,
        requiredQuest: "KINGFROGGY_QUEST_8",
        level: 30,
        xp: 300000,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 69
        }
    },
    {
        id: "NIGHTMARELAND_QUEST_1",
        name: "The King's Blue Monster Request",
        startText: ["Will you please help us restore DreamLand to it's origins by completing a series quests?",
        "The King has requested that you slay 100 blue monsters."],
        endText: "Thanks for your help whooping on those blue monsters! Are they dropping any items for you to collect?",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NNIGHTMAREMONSTERB,
        amount: 100,
        level: 1,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_2",
        name: "The King's Yellow Monster Request",
        startText: ["Thanks for whooping on those blue monsters, those are ugly little things aren't they?",
        "The King has requested that you slay 100 yellow monsters next."],
        endText: "Thanks for your help whooping on those yellow monsters! Are they dropping any items for you to collect?",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NNIGHTMAREMONSTERY,
        amount: 100,
        requiredQuest: "NIGHTMARELAND_QUEST_1",
        level: 4,
        xp: 20000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_3",
        name: "The King's Green Monster Request",
        startText: ["Thanks for whooping on those yellow monsters. Keep an eye out for unique items that they drop.", 
        "The King has requested that you slay 100 green monsters next."],
        endText: "Thanks for your help whooping on those green monsters! Are they dropping any items for you to collect?",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NNIGHTMAREMONSTERG,
        amount: 100,
        requiredQuest: "NIGHTMARELAND_QUEST_2",
        level: 6,
        xp: 30000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_4",
        name: "The King's Dark Cloud Request",
        startText: ["These dark clouds are depressing, let's clear them out of here.", 
        "The King has requested that you collect 30 dark clouds."],
        endText: "Thanks for your help gathering all of those dark clouds up",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NDARKCLOUD,
        amount: 30,
        requiredQuest: "NIGHTMARELAND_QUEST_3",
        level: 8,
        xp: 40000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_5",
        name: "The King's Dream Cloud Request",
        startText: ["We need to replace those dark clouds with a bunch of OG dream clouds, those fluffy white ones.", 
        "The King has requested that you collect 30 dream clouds."],
        endText: "Thanks for your help gathering all of those dream clouds up",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NDREAMCLOUD,
        amount: 30,
        requiredQuest: "NIGHTMARELAND_QUEST_4",
        level: 10,
        xp: 40000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_6",
        name: "The King's Aqua Monster Request",
        startText: ["There are so many of these monsters! They're all over the place!",
        "The King has requested that you slay 100 aqua monsters next."],
        endText: "Thanks for your help whooping on those aqua monsters!",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NNIGHTMAREMONSTERA,
        amount: 100,
        requiredQuest: "NIGHTMARELAND_QUEST_5",
        level: 12,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_7",
        name: "The King's Sunshine Request",
        startText: ["The last big thing we need to restore DreamLand is some sunshine!", 
        "The King has requested that you collect 30 rays of sunshine."],
        endText: "Thanks for your help gathering all of that sunshine up.",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NSUNSHINE,
        amount: 30,
        requiredQuest: "NIGHTMARELAND_QUEST_6",
        level: 14,
        xp: 69000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_8",
        name: "The King's Violet Monster Request",
        startText: ["We almost have everything we need to restore DreamLand and get back there!",
        "The King has requested that you slay 100 violet monsters next."],
        endText: "Thanks for your help whooping on those violet monsters!",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NNIGHTMAREMONSTERV,
        amount: 100,
        requiredQuest: "NIGHTMARELAND_QUEST_7",
        level: 16,
        xp: 88000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_9",
        name: "The King's Random Bones Request",
        startText: ["Do you see the suspicious graveyard over to the right?",
        "I wonder what's going on over there...", 
        "The King has requested that you collect 30 random bones so you can go check it out."],
        endText: "Thanks for your help gathering all of those random bones.",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NBONE,
        amount: 30,
        requiredQuest: "NIGHTMARELAND_QUEST_8",
        level: 18,
        xp: 69000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_10",
        name: "The King's Pink Monster Request",
        startText: ["This is the last set of monsters we need you to beat up!",
        "The King has requested that you slay 100 pink monsters."],
        endText: "Thanks for your help whooping on those pink monsters!",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NNIGHTMAREMONSTERP,
        amount: 100,
        requiredQuest: "NIGHTMARELAND_QUEST_9",
        level: 20,
        xp: 88000,
        medal: Types.Medals.SKULL
    },
    {
        id: "NIGHTMARELAND_QUEST_11",
        name: "The King's Skeleton Key Request",
        startText: ["The only thing standing between you and DreamLand is a skeleton key!",
        "The King has requested that you find the skeleton key so you can unlock the door to DreamLand."],
        endText: "Thank you for helping us restore DreamLand! Now, go enjoy higher xp rewards and more gold drops!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.KINGFROGGYBW,
        target: Types.Entities.M88NSKELETONKEY,
        amount: 1,
        requiredQuest: "NIGHTMARELAND_QUEST_10",
        level: 22,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "M88NGEM_QUEST_1",
        name: "The m88nshiner's m88n gem Request",
        startText: ["You see those m88n gems around? There is something special about them...",
        "Most people use them for currency around here.",
        "wenmoon uses them to make m88nshine and other weird concoctions up in the m88n lab.",
        "Bring me back a m88n gem and I'll give you a shot of m88nshine to try!"],
        inProgressText: ["Have you been to the Champagne Lounge yet?",
        "Sometimes they have m88nshine on hand. It goes fast though..."],
        endText: ["Hey, thanks for the m88n gem. Here's your shot of m88nshine!",
        "Once you drink this you'll have 10 seconds to kill as many mobs as you can.",
        "Wait till you see what happens..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN48,
        target: Types.Entities.M88NGEM,
        amount: 1,
        level: 10,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NSHINE,
            amount: 1
        }
    },
    {
        id: "GAMER_QUEST_1",
        name: "The Gamer's Vintage Gameboy Request",
        startText: ["I'm pretty sure I've seen some sweet vintage Gameboys around here...",
        "Can you find as many as you can and bring them back to me?",
        "There might be some cool old school games on them!"],
        inProgressText: ["Only {{remaining}} left to go...LFG!!",
        "Wouldn't it be cool if we could play LooperLands on those Gameboys?"],
        endText: ["Wow, great job collecting all of those Gameboys!",
        "Looks like they don't have any batteries in them though..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.GAMEBOY,
        amount: 69,
        level: 10,
        xp: 69420,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.m88ngem,
            amount: 10
        }
    },
    {
        id: "GAMER_QUEST_2",
        name: "The Gamer's Battery Request",
        startText: ["I've seen some batteries around here somewhere...",
        "We're gonna need them if we wanna play these Gameboys...",
        "Can you find as many as you can and bring them back to me?",
        "Hopefully they're all charged up!"],
        inProgressText: ["Only {{remaining}} left to go, keep it up!",
        "Don't worry you'll get some m88n gems for helping me find these..."],
        endText: ["Wow, great job collecting all of those batteries!",
        "Power to the players...and to the collectors ;)"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.BATTERY,
        amount: 69,
        requiredQuest: "GAMER_QUEST_1",
        level: 20,
        xp: 100000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 10
        }
    },
    {
        id: "GAMER_QUEST_3",
        name: "The Gamer's Hard Wallet Request",
        startText: ["Did you know the safest place to store your crypto is on a hard wallet?",
        "I know I've seen some around here every once in a while...",
        "Can you find as many as you can and bring them back to me?",
        "Then we can share them with our friends and make sure to keep our investments safe!"],
        inProgressText: ["Only {{remaining}} left to go...",
        "This might take a while, go bash some crabs. Trust me it helps."],
        endText: ["Wow, great job collecting all of those hard wallets!",
        "Power to the investors ;)"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.HARDWALLET,
        amount: 69,
        requiredQuest: "GAMER_QUEST_2",
        level: 30,
        xp: 100000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 10
        }
    },
    {
        id: "GAMER_QUEST_4",
        name: "The Gamer's 3D Movie Glasses Request",
        startText: ["I heard if you have some special 3D movie glasses you can actually see which shares are synthetic...",
        "Sounds weird, but it's worth a try! Can you find as many as you can and bring them back to me?",
        "Then we can try them on and see if the rumor is true!"],
        inProgressText: ["Only {{remaining}} left to go...LFG!!",
        "I've heard there are an absolute TON of synthetic shares.",
        "We should probably DRS our shares for safe keeping..."],
        endText: ["Wow, great job collecting all of those 3D movie glasses!",
        "Did you try them on yet?? Some of the shares have a little purple circle on them now!",
        "Here, have one! Maybe you can turn it into more..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.MOVIEGLASSES,
        amount: 69,
        requiredQuest: "GAMER_QUEST_3",
        level: 40,
        xp: 100000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDRSGME,
            amount: 1
        }
    },
    {
        id: "CHEF_QUEST_1",
        name: "The Chef's Steak Dinner Request",
        startText: ["I'm preparing a spectacular dinner party...",
        "Do you want to help me find the ingredients?",
        "It's not going to be easy but I'll gladly pay you in m88n gems for your time!",
        "The first thing we're going to need is the main course...steak!",
        "Can you help me find 20 yummy steaks?"],
        inProgressText: ["There's nothing like a fresh steak dinner!",
        "Only {{remaining}} left to go. Keep it up..."],
        endText: "Wow, great job collecting all of those delicious steaks!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NSTEAK,
        amount: 20,
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 3
        }
    },
    {
        id: "CHEF_QUEST_2",
        name: "The Chef's Baked Potato Request",
        startText: ["I can't think of a better side to go with steak than a baked potato!",
        "Can you help me find 20 potatoes?"],
        inProgressText: ["You're doing great, this is a huge help!",
        "Only {{remaining}} left to go..."],
        endText: "Nice, great job collecting all of those potatoes!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NPOTATO,
        amount: 20,
        requiredQuest: "CHEF_QUEST_1",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 3
        }
    },
    {
        id: "CHEF_QUEST_3",
        name: "The Chef's Tossed Salad Request",
        startText: ["We should probably make sure to be healthy and have our greens with dinner!",
        "Can you help me find 20 salads?"],
        inProgressText: ["Keep up the good work!",
        "Only {{remaining}} left to go..."],
        endText: "Awesome, great job collecting all of those salads!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NSALAD,
        amount: 20,
        requiredQuest: "CHEF_QUEST_2",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 3
        }
    },
    {
        id: "CHEF_QUEST_4",
        name: "The Chef's Ice Cold Brewski Request",
        startText: ["We're going to need something to wash all this food down with.",
        "How about we celebrate with something to loosen us up a little?!",
        "Can you help me find 20 ice cold brewskis?"],
        inProgressText: ["Keep up the great work, we're almost there!",
        "Only {{remaining}} left to go.",
        "Make sure you're not drinking those things..."],
        endText: "Cheers! Great job collecting all of those brewskis!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NBREWSKI,
        amount: 20,
        requiredQuest: "CHEF_QUEST_3",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 3
        }
    },
    {
        id: "CHEF_QUEST_5",
        name: "The Chef's Boysenberry Pie Request",
        startText: ["And for our final course, I think boysenberry pie should hit the spot!",
        "Can you help me find 20 slices of pie?"],
        inProgressText: ["Man oh man, I'm getting hungry!",
        "You're doing great though, only {{remaining}} left to go..."],
        endText: ["Ayyy! Great job collecting all of those slices of pie!",
        "Thanks so much for helping put this amazing dinner together!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NPIE,
        amount: 20,
        requiredQuest: "CHEF_QUEST_4",
        level: 10,
        xp: 120000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 3
        }
    },
    {
        id: "CHEF_QUEST_6",
        name: "The Chef's Dinner Bell Request",
        startText: ["Now we just need to let everyone know it's dinner time!",
        "Can you find a dinner bell for me?"],
        endText: ["Amazing, thanks mate! Dinner is served!",
        "There is a secret door somewhere in The Nexus that I have unlocked for you!",
        "Find it and there is a golden compass waiting beyond it.",
        "It will come in handy soon, trust me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN12,
        target: Types.Entities.M88NDINNERBELL,
        amount: 1,
        requiredQuest: "CHEF_QUEST_5",
        level: 10,
        xp: 100000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 2
        }
    },
    {
        id: "FARMERS_QUEST_1",
        name: "Farmer Joe's Shovel Request",
        startText: ["Sheesh...I'm exhausted. The only garden tool we have so far is a hand trowel!",
        "Can you can help me find some new supplies to plant another set of crops with?",
        "I'll hook you up with some m88n dirt for all your help!",
        "The first thing we're going to need is bigger shovel!",
        "Can you help me find 2 large shovels?"],
        endText: ["Thanks so much for finding those shovels!",
        "Next we're going to need lots and lots of seeds!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN13,
        target: Types.Entities.M88NSHOVEL,
        amount: 2,
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 2
        }
    },
    {
        id: "FARMERS_QUEST_2",
        name: "Farmer Joe's Seed Request",
        startText: ["Okay, while we're digging can you keep your eyes open for some seeds?",
        "A couple months ago we found some that had washed up by the shore in an unmarked bag!",
        "See if you can find like 20 bags of seeds."],
        inProgressText: ["Great job so far, keep it up!",
        "Only {{remaining}} left to go..."],
        endText: ["Thanks so much for finding those seeds!",
        "That'll keep us busy for a while.",
        "Now we just need a couple of watering cans!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN13,
        target: Types.Entities.M88NSEEDS,
        amount: 20,
        requiredQuest: "FARMERS_QUEST_1",
        level: 10,
        xp: 100000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 20
        }
    },
    {
        id: "FARMERS_QUEST_3",
        name: "Farmer Joe's Watering Can Request",
        startText: ["Sweet! We're going to start planting some of these seeds.",
        "We're going to need to water them pretty quickly though.",
        "Can you please find us 2 watering cans?"],
        endText: ["Perfect, thanks for finding those watering cans!",
        "The last thing we're going to need are some sacks to store our harvest in!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN13,
        target: Types.Entities.M88NWATERCAN,
        amount: 2,
        requiredQuest: "FARMERS_QUEST_2",
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 2
        }
    },
    {
        id: "FARMERS_QUEST_4",
        name: "Farmer Joe's Harvest Sack Request",
        startText: ["Now we're cooking!",
        "I think the last thing we need is a sack of some sort to put our harvested crops in.",
        "Can you please find us 2 burlap sacks?"],
        endText: ["Amazing, thank you so much for finding these supplies for us.",
        "This will make our life so much easier!",
        "We're happy to be your hook up while you're visiting The Nexus!",
        "Anytime you need uh...tomatoes you know where to find us!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN13,
        target: Types.Entities.M88NSACK,
        amount: 2,
        requiredQuest: "FARMERS_QUEST_3",
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 2
        }
    },
    {
        id: "MAILMAN_QUEST_1",
        name: "The Mail Man's Mail Request",
        startText: ["So, um, I have a request for some help if you have any extra time...",
        "I set my mail bag down and accidentally let a bunch of envelopes blow away.",
        "Can you help me find 20 pieces of mail?"],
        inProgressText: ["Great job so far, keep it up!",
        "Only {{remaining}} left to find..."],
        endText: ["Oh, thank goodness! You're amazing!",
        "Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN15,
        target: Types.Entities.M88NMAIL,
        amount: 20,
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 2
        }
    },
    {
        id: "MAILMAN_QUEST_2",
        name: "The Mail Man's Package Request",
        startText: ["You have a great eye and you're saving me lots of time.",
        "Would you mind helping me find some packages too?",
        "There are 20 packages around here somewhere that I need to get back to the post office.",
        "After you help me I have a cool surpise for you!"],
        inProgressText: ["Great job so far, keep it up!",
        "Only {{remaining}} left to go..."],
        endText: ["Thank you so much, I'll put in a good word for you!",
        "If you ever want to work for the post office here in The Nexus let me know!",
        "There is a secret door somewhere in Paradise Point that I unlocked for you...",
        "Find it and there is a yacht boarding ticket just for you!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN15,
        target: Types.Entities.M88NPACKAGE,
        amount: 20,
        requiredQuest: "MAILMAN_QUEST_1",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 2
        }
    },
    {
        id: "MAILMAN_QUEST_3",
        name: "The Mail Man's Mysterious Ticket Request",
        startText: ["You know that cool yacht over there? You need a special ticket to board...",
        "Find a secret hidden door somewhere in Paradise Point and there's a boarding ticket waiting for you!"],
        inProgressText: ["If I gave you a hint it wouldn't be a secret hidden door, sorry.",
        "Look harder, it's in plain view"],
        endText: ["Have fun on the Sun Chaser! I hear there is some special fishing on it for the apes!",
        "And if you're able to find the golden ticket there is a luxirious Champagne Lounge on the yacht too..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN15,
        target: Types.Entities.M88NTICKET,
        amount: 1,
        requiredQuest: "MAILMAN_QUEST_2",
        level: 10,
        xp: 100000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "EXPLORER_QUEST_1",
        name: "The Explorer's Fly Request",
        startText: ["There are so many cool little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them. I'll gladly pay you in m88n gems!",
        "Right now I'm looking for these weird little flies, can you help me find 10 of them?"],
        inProgressText: ["Only {{remaining}} left to go...",
        "These flies are the secret to something big, I just know it!"],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NFLY,
        amount: 10,
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "EXPLORER_QUEST_2",
        name: "The Explorer's June Bug Request",
        startText: ["There are so many interesting bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "Next, I'm looking for these odd little green june bugs, can you help me find 10 of them?"],
        inProgressText: ["Only {{remaining}} left to go...",
        "I know they're shiny but don't eat any of them, they taste terrible!"],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NJUNEBUG,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_1",
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "EXPLORER_QUEST_3",
        name: "The Explorer's Dung Beetle Request",
        startText: ["There are so many cool little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "Next, I'm looking for these smelly little dung beetles, can you help me find 10 of them?"],
        inProgressText: ["Follow the smell.",
        "It's what you think it is..."],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NDUNGBEETLE,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_2",
        level: 10,
        xp: 30000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "EXPLORER_QUEST_4",
        name: "The Explorer's Stick Bug Request",
        startText: ["There are so many odd little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "Next, I'm looking for these skinny little stick bugs, can you help me find 10 of them?"],
        inProgressText: ["These little buggers can be hard to find.",
        "They look like...sticks."],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NSTICKBUG,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_3",
        level: 10,
        xp: 40000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "EXPLORER_QUEST_5",
        name: "The Explorer's Snail Request",
        startText: ["There are so many weird little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "Next, I'm looking for these slimey little snails, can you help me find 10 of them?"],
        inProgressText: ["Look for the snail trail...",
        "Only {{remaining}} more to go.",
        "These snails do leave a trail don't they?"],
        endText: ["Hey, nice! Thanks for finding those for me!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NSNAIL,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_4",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "EXPLORER_QUEST_6",
        name: "The Explorer's Butterfly Request",
        startText: ["There are so many weird little bugs around The Nexus...",
        "I need to catch a bunch of them, alive, so I can study them.",
        "For my last request, I'm looking for these magical little butterflies.",
        "If you help me find 10 of them my mission will be complete!"],
        inProgressText: ["These butterflies are going to be my greatest find yet!",
        "I have somethings special to give you for all of your help!",
        "You'll find that they come in handy soon..."],
        endText: ["Hey, nice! Thanks for finding those for me!",
        "I unlocked a secret hidden door around Paradise Point somewhere.",
        "If you find it there are a pair of binoculars waiting for you!",
        "You'll need these to find what you don't know you're looking for..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN10,
        target: Types.Entities.M88NBUTTERFLY,
        amount: 10,
        requiredQuest: "EXPLORER_QUEST_5",
        level: 10,
        xp: 69000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 8
        }
    },
    {
        id: "FISHERMAN_QUEST_1",
        name: "The Fisherman's Fishing Request",
        startText: ["Did you know you there are TONS of different fish that you can catch in this ocean?",
        "You'll need a fishing pole first though.",
        "Wanna borrow one of mine to try it out before you buy your own?",
        "Grab that fishing pole right there and I'll drop a 24 hour rental pole into your inventory!"],
        endText: ["Happy fishing friend!!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN16,
        target: Types.Entities.M88NFISHINGPOLE,
        amount: 1,
        level: 10,
        xp: 1000,
        medal: Types.Medals.SKULL,
        rental: "0xb5ed38ed7bd87b69887f974d89dd91e336cba129575fd799f0e72a9e65896dcc"
    },
    {
        id: "FISHERMAN_QUEST_2",
        name: "The Fisherman's Worm Request",
        startText: ["If I had some nice plump worms I'd probably be able to catch some bigger fish...",
        "Do you think you could find me like 20 worms?",
        "I'll give you some m88n dirt to store yours in!",
        "It does something special to them..."],
        inProgressText: ["Keep up the hard work!",
        "You only have {{remaining}} more to go.",
        "I'm not going anywhere, a bad day of fishing is better than a good day at work, am I right?"],
        endText: ["Thanks for the new bait! It's working like a charm!",
        "Happy fishing friend!!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN16,
        target: Types.Entities.M88NWORM,
        amount: 20,
        requiredQuest: "FISHERMAN_QUEST_1",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 20
        }
    },
    {
        id: "CLASSYLADY_QUEST_1",
        name: "The Classy Lady's Earring Request",
        startText: ["Some of my luggage got misplaced and I can't go to the dinner party without my jewelry...",
        "Can you please find my gold earrings?"],
        endText: ["Oh thank you! I love these earrings!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN4,
        target: Types.Entities.M88NGOLDEARRINGS,
        amount: 1,
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "CLASSYLADY_QUEST_2",
        name: "The Classy Lady's Diamond Necklace Request",
        startText: ["The next piece of jewelry that I'm missing is my Diamond Necklace...",
        "Can you please keep your eyes open for that too?"],
        endText: ["Oh my goodness thank you so much! This was my grandmother's necklace!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN4,
        target: Types.Entities.M88NDIAMONDNECKLACE,
        amount: 1,
        requiredQuest: "CLASSYLADY_QUEST_1",
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "CLASSYLADY_QUEST_3",
        name: "The Classy Lady's Diamond Ring Request",
        startText: ["I lost my wedding ring! My husband will be so mad if he finds out...",
        "Can you please try to find my diamond ring? And make sure you keep this on the downlow!"],
        endText: ["Oh, my hero! Thank you so much! Do you know how much this thing is worth?!",
        "Please accept these 5 m88n gems as a reward for finding it!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN4,
        target: Types.Entities.M88NDIAMONDRING,
        amount: 1,
        requiredQuest: "CLASSYLADY_QUEST_2",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 5
        }
    },
    {
        id: "CLASSYLADY_QUEST_4",
        name: "The Classy Lady's Gold Tiara Request",
        startText: ["Okay, the last big piece of jewelry I am missing is my gold tiara.",
        "I won it when I was crowned Miss Nexus...",
        "Please look all over to help me find this!",
        "If you are able to find it I have a really special reward for you..."],
        inProgressText: ["Thank you for your help!",
        "This is the last thing I need.",
        "Then I have a cool surprise for you!"],
        endText: ["Yay! I feel complete again and now I can go to that dinner party!",
        "There is a secret door somewhere in The Nexus that I have unlocked for you!",
        "Find it and there is a golden ticket to the Champagne Lounge beyond it!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN4,
        target: Types.Entities.M88NGOLDTIARA,
        amount: 1,
        requiredQuest: "CLASSYLADY_QUEST_3",
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "FOREMAN_QUEST_1",
        name: "The Foreman's Hard Hat Request",
        startText: ["I need to add more men to my crew if I want to get this finished anytime soon...",
        "The first thing we're going to need are some hard hats to make sure everyone is safe.",
        "Can you look around and see if you can find me 10 hard hats?"],
        inProgressText: ["Thanks for your help finding these.",
        "You only have {{remaining}} more to go!",
        "Can't have any head injuries on my watch."],
        endText: ["Great job, thank you!",
        "Now we're going to need to find some work gloves!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN31,
        target: Types.Entities.M88NHARDHAT,
        amount: 10,
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 10
        }
    },
    {
        id: "FOREMAN_QUEST_2",
        name: "The Foreman's Work Gloves Request",
        startText: ["Next, my men are going to need some work gloves...",
        "Each worker is going to need a pair of them.",
        "Can you look around and see if you can find me 20 work gloves?"],
        inProgressText: ["Don't worry about how long it takes.",
        "You only have {{remaining}} more to go.",
        "I'm gonna go take a load off at the Champagne Lounge for a few."],
        endText: ["Great job, thank you!",
        "Now we're going to need to find some blueprints!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN31,
        target: Types.Entities.M88NWORKGLOVES,
        amount: 20,
        requiredQuest: "FOREMAN_QUEST_1",
        level: 10,
        xp: 30000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 10
        }
    },
    {
        id: "FOREMAN_QUEST_3",
        name: "The Foreman's Blueprint Request",
        startText: ["Finally, we're going to need some blueprints...",
        "Each worker is going to need their own copy.",
        "Can you look around and see if you can find me 10 blueprints?"],
        inProgressText: ["You're doing great.",
        "You only have {{remaining}} more to find!",
        "Keep it up kid!"],
        endText: ["Great job, thank you!",
        "Now we can get cracking on expanding Paradise Point!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN31,
        target: Types.Entities.M88NBLUEPRINT,
        amount: 10,
        requiredQuest: "FOREMAN_QUEST_2",
        level: 10,
        xp: 50000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 10
        }
    },
    {
        id: "GREASER_QUEST_1",
        name: "The Greaser's Red Rose Request",
        startText: ["See that girl in the poodle skirt over there?",
        "I'm real keen on her and want to go steady...",
        "I gotta do something to get her attention though.",
        "Can you help me find a dozen red roses to give her?"],
        inProgressText: ["Isn't she just swell?",
        "You only have {{remaining}} more roses to find!",
        "Thank you friend. Keep it up!"],
        endText: ["Ayyy, thank you!",
        "I think she'd appreciate a nice promise ring too!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN32,
        target: Types.Entities.M88NROSE,
        amount: 12,
        level: 10,
        xp: 20000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "GREASER_QUEST_2",
        name: "The Greaser's Promise Ring Request",
        startText: ["Those flowers are definitely going to get her attention!",
        "If I want everyone to know she's my gal she's gonna need a promise ring too...",
        "Do you think you could help me find something nice?",
        "That would be the bee's knees!"],
        inProgressText: ["Any luck finding something nice?",
        "I know she likes rubies..."],
        endText: ["Ayyy, thank you so much! Wish me luck!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN32,
        target: Types.Entities.M88NRUBYRING,
        amount: 1,
        requiredQuest: "GREASER_QUEST_1",
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "BUSHGUY_QUEST_1",
        name: "The Bush Guy's Clean Undies Request",
        startText: ["Pssst...Hey uh, this is sort of awkward...",
        "I was skinny dipping last night and my clothes went out with the tide.",
        "I'm hiding in this bush now because I'm naked!",
        "Can you help me find my clothes so I can get out of here?",
        "First, I'm going to need a pair of clean undies."],
        inProgressText: ["Any luck yet?",
        "No worries, I'm chillin', it's actually kind of fun in here."],
        endText: ["Oh wow, thank you so much! How about a pair of pants?"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.M88NBUSHGUY,
        target: Types.Entities.M88NCLEANUNDIES,
        amount: 1,
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 10
        }
    },
    {
        id: "BUSHGUY_QUEST_2",
        name: "The Bush Guy's Pants Request",
        startText: ["Okay, at least I have some clean undies now! Thank you!",
        "Do you think you can find me a pair of pants to wear too?"],
        inProgressText: ["Any luck yet?",
        "Not to be too picky but I'd really like a pair of blue jeans if you have a choice."],
        endText: ["Haha, sweet! You're a savior! One last thing? How about a t-shirt now?"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.M88NBUSHGUY,
        target: Types.Entities.M88NPANTS,
        amount: 1,
        requiredQuest: "BUSHGUY_QUEST_1",
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 10
        }
    },
    {
        id: "BUSHGUY_QUEST_3",
        name: "The Bush Guy's T-Shirt Request",
        startText: ["Wow, I'm so lucky you came around! Thank you for your help!",
        "Would you do me one last favor and find me a t-shirt to wear so I can get out of here?"],
        inProgressText: ["I really like those goofy crabs over there!",
        "Do you think you can find me a shirt that says like I got crabs in Paradise Point?"],
        endText: ["Haha, amazing! Thank you so much for your help friend!",
        "Believe it or not I'm actually getting use to it in here! I think I might stick around for a little longer..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.M88NBUSHGUY,
        target: Types.Entities.M88NTSHIRT,
        amount: 1,
        requiredQuest: "BUSHGUY_QUEST_2",
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL,
        needToReturn: true,
        reward: {
            item: Types.Entities.M88NDIRT,
            amount: 10
        }
    },
    {
        id: "BUTLERS_QUEST_1",
        name: "The Butler's Compass Request",
        startText: ["The portal on the far right of the second floor will bring you to a hidden island!",
        "But you're going to need a special compass to navigate yourself there..."],
        endText: ["Heyyyy, you found the compass! Now you can go ahead and checkout the island. Have fun!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN29,
        target: Types.Entities.M88NCOMPASS,
        amount: 1,
        level: 10,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "DRS_QUEST_1",
        name: "The Mysterious Hooded Entity's Request",
        startText: ["Have you been DRSing your shares?",
        "Wanna make a trade? Give me 147 of them I'll give you the key to the jail...",
        "Then you can go in there and sling pies at Kenny and the other clowns and time you want!"],
        endText: ["Sweet, thanks, I'll add these to the pile! Have fun in there!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.M88NMYSTERYHOOD,
        target: Types.Entities.M88NDRSGME,
        amount: 147,
        level: 147,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NDRSBOOK,
            amount: 1
        }
    },
    {
        id: "PIE_SLINGER_QUEST_1",
        name: "The Apes Pie Slinger Request",
        startText: ["Wanna sling some pies at these clowns? It's fun and they drop shares.",
        "You'll need a Pie Slinger first though.",
        "Wanna borrow one of mine to try it out before you buy your own?",
        "Grab that Crossbow right there and I'll drop a 24 hour rental crossbow into your inventory!"],
        endText: ["Have fun friend!!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.M88NAPE,
        target: Types.Entities.M88NPIESLINGER,
        amount: 1,
        level: 10,
        xp: 1000,
        medal: Types.Medals.SKULL,
        //rental: "0xb5ed38ed7bd87b69887f974d89dd91e336cba129575fd799f0e72a9e65896dcc"
    },
    {
        id: "BANANA_PEEL_QUEST_1",
        name: "The Apes Banana Peel Request",
        startText: ["Hey have you seen any little monkeys running around The Nexus?",
        "Those are my kiddos. I hear they've been littering banana peels all over the place...",
        "Do you mind collecting them when you see them to help keep the place clean?",
        "I'll compost them and give ya some m88n gems for your time."],
        endText: ["Have fun friend!!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.M88NAPE,
        target: Types.Entities.M88NPEEL,
        amount: 420,
        requiredQuest: "PIE_SLINGER_QUEST_1",
        level: 100,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 8
        }
    },
    {
        id: "MRCRAB_QUEST_1",
        name: "The Crab Basher's Common Request",
        startText: ["Those little crabs on the beach are annoying.",
        "Go bash 100 of them and see how much gold you collect.",
        "I'll give you a m88n gem too!"],
        inProgressText: ["Kind of fun right?!",
        "You only have another {{remaining}} to go.",
        "Keep it up!"],
        endText: "Nice job. Maybe we should open up a crab shack.",
        eventType: "KILL_MOB",
        npc: Types.Entities.NEXAN35,
        target: Types.Entities.M88NMRCRAB,
        amount: 100,
        level: 2,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 1
        }
    },
    {
        id: "MRCRAB_QUEST_2",
        name: "The Crab Basher's Uncommon Request",
        startText: ["Nice job bashing those little bastardos.",
        "Wanna start making some real money?",
        "Go bash 1000 more and I'll hook you up with 5 m88n gems!"],
        inProgressText: ["Nice job, keep it up!",
        "You only have another {{remaining}} to go.",
        "Pretty decent gold payout too huh?"],
        endText: "Haha, thanks. They keep coming back, maybe we should also start a crab extermination business.",
        eventType: "KILL_MOB",
        npc: Types.Entities.NEXAN35,
        target: Types.Entities.M88NMRCRAB,
        amount: 1000,
        requiredQuest: "MRCRAB_QUEST_1",
        level: 10,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 5
        }
    },
    {
        id: "MRCRAB_QUEST_3",
        name: "The Crab Basher's Rare Request",
        startText: ["Okay, so I landed a contract with the city.",
        "They said if we keep bashing crabs they'll pay us handsomly.", 
        "If you bash 4000 more crabs your cut will be 10 m88n gems!"],
        inProgressText: ["Keep going, you can do it!",
        "You still have another {{remaining}} to go.",
        "Maybe you should go blow off some steam at the Cornhole Casino."],
        endText: "Nice job. We should start selling crab merchandise...",
        eventType: "KILL_MOB",
        npc: Types.Entities.NEXAN35,
        target: Types.Entities.M88NMRCRAB,
        amount: 4000,
        requiredQuest: "MRCRAB_QUEST_2",
        level: 25,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 10
        }
    },
    {
        id: "MRCRAB_QUEST_4",
        name: "The Crab Basher's Epic Request",
        startText: ["The city is very pleased with the service we're providing.",
        "You up for another tour of duty?",
        "If you can bash 8888 more crabs they're gonna give us a bonus.",
        "This time your cut will be 20 m88n gems!"],
        inProgressText: ["You must be getting pretty tweaked by now huh?",
        "You still have another {{remaining}} to go.",
        "Maybe you should take a little PTSD prevention break."],
        endText: "Nice job. Take a break soldier.",
        eventType: "KILL_MOB",
        npc: Types.Entities.NEXAN35,
        target: Types.Entities.M88NMRCRAB,
        amount: 8888,
        requiredQuest: "MRCRAB_QUEST_3",
        level: 50,
        medal: Types.Medals.SKULL,
        reward: {
            item: Types.Entities.M88NGEM,
            amount: 20
        }
    }
]

exports.quests = quests;