Types = require("../../../shared/js/gametypes");
quests = [
    {
        id: "KINGFROGGY_QUEST_1",
        name: "The King's Blue Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 blue balloon dogs to see if that helps."],
        endText: "Thanks for your help popping those blue balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGB,
        amount: 100,
        level: 1,
        xp: 1000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_2",
        name: "The King's Yellow Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 yellow balloon dogs."],
        endText: "Thanks for your help popping those yellow balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGY,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_1",
        level: 4,
        xp: 1000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_3",
        name: "The King's Green Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!", 
        "The King has requested that you pop 100 green balloon dogs."],
        endText: "Thanks for your help popping those green balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGG,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_2",
        level: 6,
        xp: 1000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_4",
        name: "The King's Aqua Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 aqua balloon dogs."],
        endText: "Thanks for your help popping those aqua balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGA,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_3",
        level: 8,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_5",
        name: "The King's Violet Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 violet balloon dogs."],
        endText: "Thanks for your help popping those violet balloon dogs! It looks like we're still floating higher and higher though.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGV,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_4",
        level: 10,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_6",
        name: "The King's Pink Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 100 pink balloon dogs."],
        endText: "Thanks for your help popping those pink balloon dogs! It looks like we're still floating higher and higher though. I bet that menacing looking hotdog has a lot of helium in it.",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONDOGP,
        amount: 100,
        requiredQuest: "KINGFROGGY_QUEST_5",
        level: 12,
        xp: 10000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_7",
        name: "The King's Red Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 5 red balloon hotdogs."],
        endText: "Thanks for your help popping those red balloon hotdogs! It looks like we're still floating higher and higher though. Hmmm, I thought for sure that would do it. We have one more chance...",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONHOTDOGR,
        amount: 5,
        requiredQuest: "KINGFROGGY_QUEST_6",
        level: 20,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_8",
        name: "The King's Orange Pop Request",
        startText: ["If we can't get these darn balloon animals under control the whole cloud kingdom is going to float away!",
        "The King has requested that you pop 1 orange balloon giraffe."],
        endText: "Thanks for your help popping all of those balloon animals! You did it!! Thank you! It looks like we're going to stay in this stratosphere for now!",
        eventType: "KILL_MOB",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.BALLOONGIRAFFEO,
        amount: 1,
        requiredQuest: "KINGFROGGY_QUEST_7",
        level: 20,
        xp: 50000,
        medal: Types.Medals.SKULL
    },
    {
        id: "KINGFROGGY_QUEST_9",
        name: "The King's Mysterious Map Request",
        startText: ["Every now and then I see a mysterious map pop up around here...",
        "I wonder what would happen if you collected them? The next time you see one hang on to it!"],
        endText: "Wow, great job collecting all of those maps! What an interesting number...Keep your eyes peeled for some sort of secret portal or something...",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.KINGFROGGY,
        target: Types.Entities.M88NMAP,
        amount: 741,
        requiredQuest: "KINGFROGGY_QUEST_8",
        level: 30,
        xp: 100000,
        medal: Types.Medals.SKULL
    },
    {
        id: "GAMER_QUEST_1",
        name: "The Gamer's Vintage Gameboy Request",
        startText: ["I'm pretty sure I've seen some sweet vintage Gameboys around here...",
        "Can you help me find as many as you can? There might be some cool old school games on them!"],
        endText: "Wow, great job collecting all of those Gameboys! Looks like they don't have any batteries in them though...",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.GAMEBOY,
        amount: 69,
        level: 10,
        xp: 69420,
        medal: Types.Medals.SKULL
    },
    {
        id: "GAMER_QUEST_2",
        name: "The Gamer's Battery Request",
        startText: ["I've seen some batteries around here somewhere...we're gonna need them if we wanna play these Gameboys...",
        "Can you help me find as many as you can? Hopefully they're all charged up!"],
        endText: "Wow, great job collecting all of those batteries! Power to the players and to the collectors ;)",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.BATTERY,
        amount: 69,
        requiredQuest: "GAMER_QUEST_1",
        level: 20,
        xp: 69420,
        medal: Types.Medals.SKULL
    },
    {
        id: "GAMER_QUEST_3",
        name: "The Gamer's Hard Wallet Request",
        startText: ["Did you know the safest place to store your crypto is on a hard wallet? I know I've seen some around here every once in a while...",
        "Can you help me find as many as you can? Then we can make sure to keep our investments safe!"],
        endText: "Wow, great job collecting all of those hard wallets! Power to the investors ;)",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.HARDWALLET,
        amount: 69,
        requiredQuest: "GAMER_QUEST_2",
        level: 30,
        xp: 69420,
        medal: Types.Medals.SKULL
    },
    {
        id: "GAMER_QUEST_4",
        name: "The Gamer's 3D Movie Glasses Request",
        startText: ["I heard if you have some special 3D movie glasses you can actually see which shares are synthetic...Sounds weird, but it's worth a try!",
        "Can you help me find as many as you can? Then we can try them on and see if the rumor is true!"],
        endText: "Wow, great job collecting all of those 3D movie glasses! Did you try them on yet?? Some of the shares have a little purple circle on them now!",
        eventType: "LOOT_ITEM",
        npc: Types.Entities.NEXAN11,
        target: Types.Entities.MOVIEGLASSES,
        amount: 69,
        requiredQuest: "GAMER_QUEST_3",
        level: 40,
        xp: 69420,
        medal: Types.Medals.SKULL
    }
]

exports.quests = quests;