Types = require("../../../shared/js/gametypes");
quests = [
    {
        id: "WELCOME_QUEST_1",
        name: "Trailblazer's Sword Request",
        startText: ["Well hello there!",
        "You must be here to learn about LooperLands.",
        "To get started, head down to the bottom of this map and locate the Taiko HQ.",
        "Make sure to pick up a sword on your way there.",
        "My friend is down there and he's expecting you!",
        "Look for the double pink arrows pointing toward him.",
        "He'll have instructions for your first quest..."],
        endText: ["Looking for a quest? Look for the double pink arrows pointing toward an NPC."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC1,
        target: Types.Entities.M88NSWORD,
        amount: 1,
        level: 1,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_1",
        name: "Trailblazer's Rat Bashing Request",
        startText: ["Welcome to Taiko Town!",
        "This is one of many worlds in LooperLands, a free online multiplayer role playing game.",
        "Grab a sword out of your inventory and go bash 5 rats over behind the 11-7 to earn 1,000 bonus xp!",
        "Then head up to the Video Game store and meet the Gamer Pirate to learn more and get a new quest..."],
        endText: ["Earn bonus xp by completing certain quests!"],
        eventType: "KILL_MOB",
        npc: Types.Entities.TAIKOTOWNNPC2,
        target: Types.Entities.RAT,
        amount: 5,
        level: 2,
        requiredQuest: "WELCOME_QUEST_1",
        xp: 1000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_2",
        name: "Trailblazer's Retro Joystick Request",
        startText: ["Hey there fellow gamer!",
        "Slaying enemies is one way to earn xp and level your assets up here in LooperLands.",
        "Another way is by completing loot quests for bonus xp.",
        "If you head over to the Pet Store you should see some retro joysticks along the way.",
        "Collect 3 of them and then meet the owner of the Pet Store to learn more and get a new quest..."],
        endText: ["Some items are consumables that have extra utility like temporary bonuses or even unlocking doors!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC3,
        target: Types.Entities.M88NJOYSTICK,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_1",
        level: 3,
        xp: 2000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_3",
        name: "Trailblazer's Pink Balloon Dog Request",
        startText: ["So LooperLands is free to play, but F2P assets will not retain their progress or level.",
        "Right now you have a lower level sword.",
        "Head back down to the Taiko HQ and pop 1 Pink Balloon Dog and notice how many hits it takes.",
        "Once you do, come back for another quest and I'll drop a 24 hour rental high level weapon in your inventory!"],
        endText: ["Lower level assets do less damage to enemies!"],
        eventType: "KILL_MOB",
        npc: Types.Entities.TAIKOTOWNNPC4,
        target: Types.Entities.BALLOONDOGP,
        amount: 1,
        requiredQuest: "TRAILBLAZER_QUEST_2",
        level: 4,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_4",
        name: "Trailblazer's Second Pink Balloon Dog Request",
        startText: ["Welcome back! Okay, use your new weapon to go back down to Taiko HQ and pop 1 more Pink Balloon Dog.",
        "Notice how much easier it is to pop them with this higher level weapon.",
        "To purchase an asset that can level up, you can browse a bunch of integrated assets in our shop.",
        'Click <a target="_blank" href="https://looperlands.io/shop">this link</a> to browse the LooperLands shop.',
        "Then head up to the bridge and meet that sketchy snail to learn more and get a new quest..."],
        endText: ["Higher level assets do more damage to enemies!"],
        eventType: "KILL_MOB",
        npc: Types.Entities.TAIKOTOWNNPC4,
        target: Types.Entities.BALLOONDOGP,
        amount: 1,
        requiredQuest: "TRAILBLAZER_QUEST_3",
        level: 5,
        xp: 3000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_5",
        name: "Trailblazer's Rubber Ducky Request",
        startText: ["Did you know you can also go fishing in LooperLands and catch epic fish that give you special power ups?!",
        "Head over to the pond and collect 3 Rubber Duckies once you do I'll drop a 24 hour rental fishing pole in your inventory!",
        "When you're finished with training feel free to hang at the pond and do some fishing!",
        "But first, head across the street and meet the guy standing in front of the Taiko building to get a new quest..."],
        endText: ["Own a fishing pole to go fishing in LooperLands!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC5,
        target: Types.Entities.M88NDUCKY,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_4",
        level: 6,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_6",
        name: "Trailblazer's Luggage Request",
        startText: ["Awesome job! We're just about done for today. I hope you're having fun and come back soon!",
        "Your last task is to collect 3 pieces of Luggage on your way over to the Goose Transit Station.",
        "Once you get there, go inside the station and talk to the girl in there to get your free mint!"],
        endText: ["Now you're ready to explore any of the worlds in LooperLands!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC6,
        target: Types.Entities.M88NLUGGAGE,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_5",
        level: 7,
        xp: 4000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_7",
        name: "Trailblazer's Bronze Medal Request",
        startText: ["Thanks for joining us and playing today!",
        'Follow <a target="_blank" href="https://looperlands.io/mint/trailblazers">this link</a> to get your free mint!',
        "That will give you an xp multiplier. Also, grab your medal out of that chest to get 10,000 bonus xp for joining us today!"],
        endText: ["We hope to see you back in here soon!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC7,
        target: Types.Entities.M88NBRONZEMEDAL,
        amount: 1,
        requiredQuest: "TRAILBLAZER_QUEST_6",
        level: 8,
        xp: 10000,
        medal: Types.Medals.HEARTH
    }

]

exports.quests = quests;