Types = require("../../../shared/js/gametypes");
quests = [
    {
        id: "TRAILBLAZER_QUEST_1",
        name: "Trailblazer's Rat Bashing Request",
        startText: ["Welcome to Taiko Town!",
        "This is one of many worlds in LooperLands, a free online multiplayer role playing game.",
        "Grab a sword and go bash 5 rats over behind the 11-7 and come back for a reward and more instructions!"],
        endText: ["Nice job! You earned some xp from each of those rats you bashed.",
        "I also awarded you 1,000 bonus xp for completing the quest!",
        "Head up to the Video Game store and meet the Gamer Pirate to learn more and get a new quest..."],
        eventType: "KILL_MOB",
        npc: Types.Entities.TAIKOTOWNNPC2,
        target: Types.Entities.RAT,
        amount: 5,
        level: 1,
        xp: 1000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_2",
        name: "Trailblazer's Retro Joystick Request",
        startText: ["Hey there fellow gamer!",
        "Slaying enemies is one way to earn xp and level your assets up here in LooperLands.",
        "Another way is by completing quests for bonus xp.",
        "If you head over to the Pet Store you should see some retro joysticks along the way.",
        "Collect 3 of them and report back to me for a reward and further instructions!"],
        endText: ["Great job! Some items are consumables that have extra utility like temporary bonuses or even unlocking doors!",
        "But not these ones. So I awarded you 2,000 bonus xp for completing this quest!",
        "Head back over to the Pet Store and meet the owner to learn more and get a new quest..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC3,
        target: Types.Entities.M88NJOYSTICK,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_1",
        level: 1,
        xp: 2000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_3",
        name: "Trailblazer's Pink Balloon Dog Request",
        startText: ["So LooperLands is free to play, but F2P assets will not retain their progress or level.",
        "Right now you have a lower level sword.",
        "Head back down to the Taiko HQ and pop 1 Pink Balloon Dog and notice how many hits it takes.",
        "Then come back here to get a reward!"],
        endText: ["Nice job! Kind of tough with a lower level weapon huh?",
        //'Click <a target="_blank" href="https://loopexchange.art/collection/assets-for-looperlands">this link</a> to get a free 24 hour rental of a higher level weapon.',
        "Then come back for another quest..."],
        eventType: "KILL_MOB",
        npc: Types.Entities.TAIKOTOWNNPC4,
        target: Types.Entities.BALLOONDOGP,
        amount: 1,
        requiredQuest: "TRAILBLAZER_QUEST_2",
        level: 1,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_4",
        name: "Trailblazer's Second Pink Balloon Dog Request",
        startText: ["Welcome back! Okay, use your new weapon to go back down to Taiko HQ and pop 3 more Pink Balloon Dogs.",
        "Notice how much easier it is to pop them with this higher level weapon.",
        "Then come back here to get a reward!"],
        endText: ["Nice job! Way easier this time huh? Here's 3,000 bonus xp for completing that quest!",
        "To purchase an asset that can level up, you can browse a bunch of integrated assets in our shop.",
        //'Click <a target="_blank" href="https://loopexchange.art/collection/assets-for-looperlands">this link</a> to browse the LooperLands shop.',
        "Next, head up to the bridge and meet that sketchy snail to learn more and get a new quest..."],
        eventType: "KILL_MOB",
        npc: Types.Entities.TAIKOTOWNNPC4,
        target: Types.Entities.BALLOONDOGP,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_3",
        level: 1,
        xp: 3000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_5",
        name: "Trailblazer's Rubber Ducky Request",
        startText: ["Did you know you can also go fishing in LooperLands and catch epic fish that give you special power ups?!",
        "Head over to the pond and collect 3 Rubber Duckies, and then come back to receive a link for a free rental fishing pole!"],
        endText: ["Wow, you're doing great! Here's a link for a rental fishing pole...",
        //'Click <a target="_blank" href="https://loopexchange.art/collection/assets-for-looperlands">this link</a> to browse the LooperLands shop.',
        "When you're finished with training feel free to hang at the pond and do some fishing!",
        "But first, head across the street and meet the guy standing in front of the Taiko building to learn more and get a new quest..."],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC5,
        target: Types.Entities.M88NDUCKY,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_4",
        level: 1,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_6",
        name: "Trailblazer's Luggage Request",
        startText: ["Awesome job! We're just about done for today. I hope you're having fun and come back soon!",
        "Your last task is to collect 3 pieces of Luggage on your way over to the Goose Transit Station.",
        "Once you get there, go inside the station and talk to the girl in there to get your free mint!"],
        endText: ["Great job finding those pieces of luggage! Now you're ready to explore any of the worlds in LooperLands!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC6,
        target: Types.Entities.M88NLUGGAGE,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_5",
        level: 1,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_7",
        name: "Trailblazer's Bronze Medal Request",
        startText: ["Thanks for joining us and playing today!",
        //'Follow <a target="_blank" href="https://loopexchange.art/collection/assets-for-looperlands">this link</a> to get your free mint!',
        "That will give you an xp multiplier. Also, grab your medal out of that chest to get 10,000 bonus xp for joining us today!"],
        endText: ["We hope to see you back in here soon!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC7,
        target: Types.Entities.M88NBRONZEMEDAL,
        amount: 1,
        requiredQuest: "TRAILBLAZER_QUEST_6",
        level: 1,
        xp: 10000,
        medal: Types.Medals.HEARTH
    }

]

exports.quests = quests;