Types = require("../../../shared/js/gametypes");
quests = [
    {
        id: "TRAILBLAZER_QUEST_1",
        name: "Trailblazer's Rat Bashing Request",
        startText: ["Welcome to Taiko Town!",
        "Grab a sword out of your inventory, head NORTH, and go bash a rat over behind the 11-7 to earn 1,000 bonus xp!",
        "Then take a short walk NORTH/WEST to the Video Game store and meet the Gamer Pirate to get a new quest..."],
        endText: ["Earn bonus xp by completing certain quests!"],
        eventType: "KILL_MOB",
        npc: Types.Entities.TAIKOTOWNNPC2,
        target: Types.Entities.RAT,
        amount: 1,
        level: 1,
        xp: 1000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_2",
        name: "Trailblazer's Retro Joystick Request",
        startText: ["Hey there fellow gamer!",
        "Head WEST to the Pet Store and collect 3 retro joysticks along the way.",
        "Then meet the Pet Store owner to get a new quest..."],
        endText: ["Some items are consumables that have extra utility like temporary bonuses or even unlocking doors!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC3,
        target: Types.Entities.M88NJOYSTICK,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_1",
        level: 2,
        xp: 2000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_3",
        name: "Trailblazer's Pink Balloon Dog Request",
        startText: ["Greetings!",
        "Right now you have a lower level sword.",
        "Head SOUTH to the Taiko HQ and pop 1 Pink Balloon Dog and notice how many hits it takes.",
        "Then come back for another quest and I'll drop a higher level rental weapon in your inventory!"],
        endText: ["Lower level assets do less damage to enemies!"],
        eventType: "KILL_MOB",
        npc: Types.Entities.TAIKOTOWNNPC4,
        target: Types.Entities.BALLOONDOGP,
        amount: 1,
        requiredQuest: "TRAILBLAZER_QUEST_2",
        level: 3,
        medal: Types.Medals.HEARTH,
        rental: "0x139b4906d04d012fd7b296bb06182b67d9f88734cf89a1de9b87e97508a82500"
    },
    {
        id: "TRAILBLAZER_QUEST_4",
        name: "Trailblazer's Second Pink Balloon Dog Request",
        startText: ["Okay, now go back to Taiko HQ and pop 1 more Pink Balloon Dog with your new weapon.",
        "Make sure to notice how much easier it is to pop them with this higher level weapon.",
        "Then head NORTH to the overpass and meet that sketchy snail to get a new quest..."],
        endText: ["Higher level assets do more damage to enemies!"],
        eventType: "KILL_MOB",
        npc: Types.Entities.TAIKOTOWNNPC4,
        target: Types.Entities.BALLOONDOGP,
        amount: 1,
        requiredQuest: "TRAILBLAZER_QUEST_3",
        level: 4,
        xp: 3000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_5",
        name: "Trailblazer's Rubber Ducky Request",
        startText: ["Head NORTH to the pond and collect 3 Rubber Duckies to get a rental fishing pole dropped in your inventory!",
        "Then, head EAST across the street and meet the guy standing in front of the Taiko building to get a new quest...",
        "When you're all finished with the training feel free to hang at the pond and do some fishing!"],
        endText: ["Own a fishing pole to go fishing in LooperLands!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC5,
        target: Types.Entities.M88NDUCKY,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_4",
        level: 5,
        medal: Types.Medals.HEARTH,
        rental: "0x344ec7868b6f0fc509e79ddf53b1320ce875673150cae151dd9cbd2764d96273"
    },
    {
        id: "TRAILBLAZER_QUEST_6",
        name: "Trailblazer's Luggage Request",
        startText: ["Awesome job! We're just about done for today. I hope you're having fun and come back soon!",
        "Your last task is to collect 3 pieces of Luggage on your walk over (EAST) to the Goose Transit Station.",
        "Once you get there, go inside the station and talk to the girl in there to get your free mint!"],
        endText: ["Now you're ready to explore any of the worlds in LooperLands!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC6,
        target: Types.Entities.M88NLUGGAGE,
        amount: 3,
        requiredQuest: "TRAILBLAZER_QUEST_5",
        level: 6,
        xp: 4000,
        medal: Types.Medals.HEARTH
    },
    {
        id: "TRAILBLAZER_QUEST_7",
        name: "Trailblazer's Bronze Medal Request",
        startText: ["Thanks for joining us and playing today!",
        'Follow <a target="_blank" href="https://looperlands.io/mint/trailblazers">this link</a> to get your free mint!',
        "That will give you an xp multiplier. Also, grab your medal out of that chest to get 10,000 bonus xp for joining us today!"],
        endText: ["We hope to see you back in here soon!"],
        eventType: "LOOT_ITEM",
        npc: Types.Entities.TAIKOTOWNNPC7,
        target: Types.Entities.M88NBRONZEMEDAL,
        amount: 1,
        requiredQuest: "TRAILBLAZER_QUEST_6",
        level: 7,
        xp: 10000,
        medal: Types.Medals.HEARTH
    }

]

exports.quests = quests;