const AltNames = {
    skeleton2: 'greater skeleton',
    eye: 'evil eye',
    deathknight: 'death knight',
    cobslimeblue: "Blinky",
    cobslimeyellow: "Winky",
    cobslimered: "Inky",
    cobslimepurple: "Plum",
    cobslimegreen: "Glimmer",
    cobslimepink: "Pinky",
    cobslimecyan: "Zippy",
    cobslimemint: "Minty",
    cobslimeking: "slime king",
    magcrack: "megamag",
    cobdirt: "pile of dirt",
    cobincubator: "egg incubator",
    cobcoblin: "coblin",
    cobcobane: "cobane",
    cobogre: "ogre",
    cobfallingrock: "falling rock",
    cobguppy: "guppy",
    cobneon: "neon tetra",
    cobgoldfish: "goldfish",
    cobtrout: "trout",
    cobcatfish: "catfish",
    coblobster: "red lobster",
    cobsardine: "sardine",
    cobwhiting: "whiting",
    cobangelfish: "angel fish",
    cobstingray: "stingray",
    fishingrod: "Fishing Rod",
    weapon: "Weapon",
    cobrosette: "rosette",
    cobparadisefish: "paradise fish",
    cobfatheadminnow: "fathead minnow",
    cobgrasscarp: "grass carp",
    cobgreensunfish: "green sunfish",
    cobcruciancarp: "crucian carp",
    cobbluegill: "bluegill",
    ////OA FISHIES
    oagreyeverfish: "Grey Everfish",
    oafish1: "Grey Everfish",
    oafish2: "Umber Tideglider",
    oafish3: "Great Grayscale",
    oafish4: "Sunny Reefrascal",
    oafish5: "Emerald Mischief",
    oafish6: "Violet Trickster",
    oafish7: "Aqua Jestfish",
    oafish8: "Lumin Everglow",
    oafish9: "Clam of Radiance",
    oafish10: "Nocturne Shellmyst",
    oafish11: "Fantasea Roamer",
    oafish12: "Mythfin Drifter",
    oafish13: "Crimson Squidleap",
    oafish14: "Teal Tentaflash",
    oafish15: "Spiral Squidshell",
    oafish16: "Verde Shellswim",
    oafish17: "Cocoa Helmfloat",
    oafish18: "Everfrond Seawhisper",
    oafish19: "Sunset Skulkprawn",
    oafish20: "Duskpincher",
    oafish21: "Ruby Starfloat",
    oafish22: "Abyssal Evershark",
    oafish23: "Azure Finstealth",
    oafish24: "Verdant Sharkwave",
    oafish25: "Cerulean Wonderfin",
    oafish26: "Scarlet Mysticfish",
    oafish27: "Jade Specterfin",
    oafish28: "Lavender Lorefish",
    oafish29: "Tangerine Medusozoa",
    oafish30: "Crimson Seahaven",
    oafish31: "Sandy Shellecho",
    oafish32: "Garnet Clamharbor",
    oafish33: "Tropic Pinchmarvel",
    oafish34: "Cobalt Asteroidea",
    oafish35: "Orbhead Oceantwirl",
    oafish36: "Emerald Jellyfloat",  

    //Short Destroyers
    lateflea: ".65 Late Flea",  
    wolfboss: "Jeff",  
    horde1: ".65 Late Flea",  
    horde2: ".65 Late Flea",  
    horde3: ".65 Late Flea",  
    horde4: ".65 Late Flea",  
    horde5: ".65 Late Flea", 
    fleaboss: "Giant Late Flea",

    //m88n Fishing
    m88ndreamduckyy: "the Yellow Rubber Ducky",  
    m88ndreamduckyg: "the Green Rubber Ducky",  
    m88ndreamduckyb: "the Blue Rubber Ducky",  
    m88ndreamduckyp: "the Purple Rubber Ducky",  
    m88ndreamduckyr: "the Red Rubber Ducky",
    m88ndreamcandyy: "the Yellow Lemonhead",
    m88ndreamcandyo: "the Orange Gobstopper",
    m88ndreamcandya: "the Tropical Warhead",  
    m88ndreamcandyg: "the Green Apple Gobstopper",  
    m88ndreamcandyb: "the Blue Raspberry Warhead",  
    m88ndreamcandyp: "the Guava Gobstopper",  
    m88ndreamcandyr: "the Fireball",
    m88ndreamgumbally: "the Banana Gumball",
    m88ndreamgumballo: "the Mango Gumball",
    m88ndreamgumballa: "the Cotton Candy Gumball",  
    m88ndreamgumballg: "the Sour Apple Gumball",  
    m88ndreamgumballb: "the Blueberry Gumball",  
    m88ndreamgumballp: "the OG Gumball",  
    m88ndreamgumballr: "the Cinnamon Gumball",
    m88ngmeshare: "1 GME share",  
    m88nwhiskey: "free whiskey",  
    m88ndiamondhand: "a diamond hand",  
    m88ngoldenbanana: "a golden banana",  
    m88nshorts: "the shorts",
    m88nseafrog: "a sea frog",
    m88nseahorse: "a sea horse",
    m88nseaurchin: "a sea urchin",
    m88nstarfish: "a starfish",
    m88nseaweed: "some seaweed",
    m88nspirula: "a spirula",
    m88nshrimp: "a skrimp",
    m88nsilvereel: "a silver eel",
    m88npinkfantasia: "a pink fantasia",
    m88npiranha: "a piranha",
    m88nscallop: "a scallop",
    m88nsaltwatersnail: "a salt water snail",
    m88nseaspider: "a sea spider",
    m88noctopus: "an octopus",
    m88npufferfish: "a pufferfish",
    m88nseacucumber: "a sea cucumber",
    m88ntigerfish: "a tiger fish",
    m88nguppy: "a guppy",
    m88nkoifish: "a koi fish",
    m88nturtle: "a turtle",
    m88nsanddollar: "a sand dollar",
    m88njellyfish: "a jellyfish",
    m88nlionfish: "a lion fish",
    m88nsundial: "a sun dial",
    m88ntuna: "a tuna",
    m88ncharfish: "a char fish",
    m88ncrab: "a crab",
    m88ncowfish: "a cow fish",
    m88nlampreyeel: "a lamprey eel",
    m88nbluelobster: "a blue lobster",
    m88nparrotfish: "a parrot fish",
    m88nconch: "a conch",
    m88ndumbooctopus: "a dumbo octopus",
    m88nbettafish: "a betta fish",
    m88nsquid: "a squid",
    m88nnautilus: "a nautilus",
    m88nwolffish: "a wolf fish",
    m88nblobfish: "a blob fish",
    m88nclownfish: "a clown fish",
    m88noyster: "an oyster",
    m88npearl: "a pearl",
    m88naxolotl: "an axolotl",
    m88nbutterflyfish: "a butterfly fish",
    m88ncoral: "some coral",
    m88nseaangel: "a sea angel",
    m88nanglerfish: "an angler fish",
    m88nbluetang: "a blue tang",
    m88nclam: "a clam",
    m88npompano: "a pompano",
    m88nmackerel: "a mackerel",
    m88noceanbass: "an ocean bass",

    //MRMlabs Fishing
    bbqchips: "BBQ chips",  
    saltnvinegarchips: "salt and vinegar chips",
    blackpepperchips: "black pepper chips",  
    dillpicklechips: "dill pickle chips",
    berryblast: "berry blast soda",
    cherrycola: "cherry cola",
    gingerale: "ginger ale",
    rootbeer: "root beer",
    valleydew: "valley dew soda",

    //m88n Mobs
    balloondogb: "Blue Balloon Dog",  
    balloondogy: "Yellow Balloon Dog",  
    balloondogg: "Green Balloon Dog",  
    balloondoga: "Aqua Balloon Dog",  
    balloondogp: "Pink Balloon Dog",
    balloondogv: "Violet Balloon Dog",
    balloonhotdogr: "Red Balloon Hotdog",
    balloongiraffeo: "Orange Balloon Giraffe",
    m88nbabymonkey: "Baby Monkey",
    m88nbabyape: "Baby Ape",
    m88nbabychimp: "Baby Chimp",
    m88nbabyturtle: "Baby Turtle",
    m88nbabypenguin: "Baby Penguin",
    m88ndaddyape: "Daddy Ape",
    m88ndaddypenguin: "Daddy Penguin",
    m88ndaddyturtle: "Daddy Turtle",
    m88nparrot: "Parrot",
    m88ntoucan: "Toucan",
    m88nseal: "Seal",
    m88nwalrus: "Walrus",
    m88noctopussy: "Octopussy",
    m88nmagiccarpet: "Magic Carpet",
    m88nhermie: "Hermie",
    m88nmrcrab: "Mr. Crab",
    m88nmine: "m88n mine",
    m88npinataballoons: "prize balloons!",

    //m88n Mob Nexans
    nexan8: "The Mail Lady",
    nexan9: "The Ship Captain",
    nexan11: "The Gamer",
    nexan12: "The Chef",
    nexan13: "Farmer Joe",
    nexan14: "Farmer Jon",
    nexan15: "The Mail Man",
    nexan30: "The Bartender",
    m88njeeves: "Jeeves",

    //m88n NPCs
    nexan29: "The Butler",
    thehookup: "The Hookup",
    m88nbushguy: "Bush Guy",
    m88nsignguy: "Sign Guy",
    m88nmysteryhood: "Mystery Hooded Guy",
    m88ntaikotwin1: "Taiko Twin 1",
    m88ntaikotwin2: "Taiko Twin 2",
    m88nstimytimy: "Stimy Timy",
    m88nrealtyagent: "Real Estate Agent",
    m88ngenie: "Magic Genie!",
    nexan32: "The Greaser",
    nexan10: "Darwin",

    //m88n Items
    m88nmail: "mail",
    m88nfastshoes: "a pair of fast shoes",
    m88nslowshoes: "a pair of slow shoes",
    m88nwizardshat: "a Wizard's hat",
    m88nbrassknuckles: "brass knuckles",
    m88nkevlararmor: "kevlar armor",
    m88ngrenade: "a grenade",
    m88ndinnerbell: "a dinner bell",
    m88npants: "pants",
    m88ntshirt: "a t-shirt",
    m88ngoldmedal: "gold medal",
    m88nsilvermedal: "silver medal",
    m88nbronzemedal: "bronze medal",
    m88nfishingpole: "fishing pole",
    m88nprizes: "mysterious prizes",
    m88nlamp: "a mysterious lamp",
    m88ngemticket: "a m88n mine ticket",

    //m88n TT Items
    m88nammocan: "ammo can",
    m88nbanana: "banana",
    m88nbasketball: "basketball",
    m88nblueprint: "blueprint",
    m88nbnote: "beamed note",
    m88nbone: "bone",
    m88ncarrot: "carrot",
    m88ncheese: "cheese",
    m88nchocolate: "chocolate",
    m88ncleanundies: "clean undies",
    m88ndogcollar: "dog collar",
    m88nducky: "rubber ducky",
    m88nenote: "eighth note",
    m88nfancyhat: "fancy hat",
    m88nglowstick: "glow stick",
    m88nguitar: "guitar",
    m88nhardhat: "hard hat",
    m88nhockeystick: "hockey stick",
    m88nipod: "iPod",
    m88njoystick: "retro joystick",
    m88nlettermanjacket: "letterman jacket",
    m88nluggage: "luggage",
    m88npolicebadge: "police badge",
    m88npolicehat: "police hat",
    m88nqnote: "quarter note",
    m88nrainbow: "rainbow",
    m88nrolex: "Rolex",
    m88nrollingpin: "rolling pin",
    m88nrose: "red rose",
    m88nrubyring: "ruby ring",
    m88nshades: "shades",
    m88nsnote: "sixteenth note",
    m88nsnowflake: "snowflake",
    m88ntp: "tp",
    m88nworkgloves: "work glove",
    m88ncheesepizza: "cheese pizza",
    m88npizza: "pizza",
    m88nsword: "sword",

    //Taiko Town NPCs
    taikotownnpc1: "I am NPC",

    //Duckville Fishing
    dragonegg: "a dragon egg",
    dragonbreath: "some dragon breath",
    dragonclaw: "a dragon claw",
    luckybabydragon: "a lucky baby dragon",

    //BITCORN PHISHIES
    bit_BoneFish: "a BoneFish",
    bit_Corn: "RIVER CORN!",
    bit_FEET: "FEET",
    bit_freshPrawnce: "The Fresh Prawnce",
    bit_JEFF: "JEFF",
    bit_Kickle: "Kickle the Pickle",
    bit_maCORNtosh: "one of dem' maCORNtosh CORNputers",
    bit_MrPunchy: "Mr. Punchy",
    bit_SnaggletoothEel: "a nasty Snaggletooth Eel!",
    bit_NOPEmato: "a NOPEmato",
    cornBootFish: "Old Gregg's Shoe",
    cornCanFish: "an empty can of Mother Shucker",
    cornWinkyFish: "The Legendary Winky",

    devon: "Chase", 
};

AltNames.getAltNameFromKind = function(kind){
    if(kind in AltNames) {
        return AltNames[kind];
    }
};

AltNames.getName = function (kind){
    let altName = AltNames.getAltNameFromKind(kind);
    return altName !== undefined ? altName : kind;
};

if(!(typeof exports === 'undefined')) {
    module.exports = AltNames;
}