
name: Docker Hub Login and Image Push
on:
  pull_request:
    branches: [ main ]

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t balkshamster/looperlands:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push balkshamster/looperlands:latest

