name: Quality Check

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0' # Specify your project's Node.js version
    - name: Install dependencies
      run: npm install
    - name: Run linter
      run: npx eslint client --ext .js,.jsx,.ts,.tsx --quiet && npx eslint server --ext .js,.jsx,.ts,.tsx --quiet && npx eslint shared --ext .js,.jsx,.ts,.tsx --quiet
    - name: Run unit tests
      run: npm run coverage